"""LATENTIS Synthetic Data Generator package (Phase 2).

Owner: Data + ML Engineer (worker-data-ml-engineer)
Charter: Owns datagen/**, pure numeric core, and model artifacts.
Invariants:
  - DR-01: Synthetic dataset generated by seeded, specified generator.
  - DR-03: Every generator parameter carries a provenance tag (TEST-GEN-001).
  - DR-10: Generator cannot import model code (backend/core/**).
"""

from __future__ import annotations

from datagen.artifacts import (
    DatasetArtifactsResult,
    generate_dataset,
)
from datagen.config import (
    DatagenConfig,
    DegradationClass,
    InvalidProvenanceError,
    MissingProvenanceError,
    ProvenanceTag,
    ProvenanceTagError,
    TaggedParameter,
    UntaggedParameterError,
    get_default_config,
    load_config,
)
from datagen.generator import SyntheticDataGenerator
from datagen.imperfections import (
    ImperfectionInjector,
    ImperfectionResult,
    MeasurementRecord,
    convert_lot_to_records,
    convert_part_to_records,
    inject_censoring,
    inject_duplicates,
    inject_missing_rows,
    inject_msa_noise,
    inject_timestamp_jitter,
    inject_unit_inconsistencies,
)
from datagen.labels import (
    PartLabelResult,
    check_absolute_limits,
    compute_drift_and_anomaly_metrics,
    derive_failure_label,
    derive_is_escape,
    derive_labels_for_lot,
    derive_labels_for_part,
    derive_must_flag,
    derive_stratum,
    recompute_ground_truth_labels,
)
from datagen.physics import (
    ArrheniusModel,
    BaselineDraw,
    DegradationShapeModel,
    DegradationTrajectory,
    FactorCorrelationModel,
    PhysicalModel,
    ShapeFamily,
    ThermalZone,
)
from datagen.profile import (
    generate_dataset_profile,
)
from datagen.splits import (
    SplitAssignment,
    assign_lot_disjoint_splits,
    compute_mondrian_calibration_stats,
    generate_split_audit_report,
    verify_lot_disjointness,
)
from datagen.strata import (
    DECOY_STRATA,
    ESCAPE_STRATA,
    FLAGGED_TARGET_STRATA,
    FailureLabel,
    StrataGenerator,
    StratifiedLot,
    Stratum,
    StratumPart,
    check_values_inside_limits,
    classify_rendered_stratum,
    find_limit_violations,
    is_decoy,
    is_escape,
    must_flag,
)

__all__ = [
    "DECOY_STRATA",
    "ESCAPE_STRATA",
    "FLAGGED_TARGET_STRATA",
    "ArrheniusModel",
    "BaselineDraw",
    "DatagenConfig",
    "DatasetArtifactsResult",
    "DegradationClass",
    "DegradationShapeModel",
    "DegradationTrajectory",
    "FactorCorrelationModel",
    "FailureLabel",
    "ImperfectionInjector",
    "ImperfectionResult",
    "InvalidProvenanceError",
    "MeasurementRecord",
    "MissingProvenanceError",
    "PartLabelResult",
    "PhysicalModel",
    "ProvenanceTag",
    "ProvenanceTagError",
    "ShapeFamily",
    "SplitAssignment",
    "StrataGenerator",
    "StratifiedLot",
    "Stratum",
    "StratumPart",
    "SyntheticDataGenerator",
    "TaggedParameter",
    "ThermalZone",
    "UntaggedParameterError",
    "assign_lot_disjoint_splits",
    "check_absolute_limits",
    "check_values_inside_limits",
    "classify_rendered_stratum",
    "compute_drift_and_anomaly_metrics",
    "compute_mondrian_calibration_stats",
    "convert_lot_to_records",
    "convert_part_to_records",
    "derive_failure_label",
    "derive_is_escape",
    "derive_labels_for_lot",
    "derive_labels_for_part",
    "derive_must_flag",
    "derive_stratum",
    "find_limit_violations",
    "generate_dataset",
    "generate_dataset_profile",
    "generate_split_audit_report",
    "get_default_config",
    "inject_censoring",
    "inject_duplicates",
    "inject_missing_rows",
    "inject_msa_noise",
    "inject_timestamp_jitter",
    "inject_unit_inconsistencies",
    "is_decoy",
    "is_escape",
    "load_config",
    "must_flag",
    "recompute_ground_truth_labels",
    "verify_lot_disjointness",
]
