"""Synthetic dataset generator for burn-in degradation and screening (Phase 2).

Owner: Data + ML Engineer
Charter: Pure numeric core, datagen/**, model artifacts.
Invariants:
  - DR-01: Synthetic dataset generated by seeded, specified generator.
  - DR-03: Every generator parameter carries a provenance tag (TEST-GEN-001).
  - DR-10: Generator cannot import model code (backend/core/**).
"""

from __future__ import annotations

from pathlib import Path
from typing import Any

from datagen.config.loader import get_default_config, load_config
from datagen.config.provenance import (
    ProvenanceTag,
    UntaggedParameterError,
    extract_parameter_manifest,
)
from datagen.config.schema import DatagenConfig


class SyntheticDataGenerator:
    """Forward simulator of physical and statistical burn-in degradation.

    Implements: DATA_GENERATION_SPEC.md, DATASET_SPEC.md.
    Enforces: TEST-GEN-001 (Refuses to start if any parameter lacks provenance).
    """

    def __init__(
        self,
        config: DatagenConfig | dict[str, Any] | Path | str | None = None,
    ) -> None:
        """Initialize the synthetic generator with strict provenance verification.

        Args:
            config: DatagenConfig, config dict, file path, or None (default config).

        Raises:
            UntaggedParameterError: If any parameter lacks provenance metadata (TEST-GEN-001).
            InvalidProvenanceError: If provenance tags are invalid.
            ValidationError: If schema validation fails.
        """
        if config is None:
            self.config = get_default_config()
        elif isinstance(config, DatagenConfig):
            # Direct DatagenConfig instance: verify provenance of all parameters
            self.config = config
            manifest = extract_parameter_manifest(self.config)
            for entry in manifest:
                if entry["provenance"] not in {p.value for p in ProvenanceTag}:
                    raise UntaggedParameterError(
                        f"Parameter '{entry['path']}' has invalid provenance "
                        f"'{entry['provenance']}'."
                    )
        else:
            self.config = load_config(config)

        # Confirm 100% of parameters carry legitimate provenance tags
        self._manifest = extract_parameter_manifest(self.config)
        for p in self._manifest:
            if not p.get("provenance"):
                raise UntaggedParameterError(
                    f"Parameter '{p['path']}' has missing provenance tag (TEST-GEN-001)."
                )

        # Initialize physical model simulation engine (T-202)
        from datagen.imperfections import ImperfectionInjector
        from datagen.physics import PhysicalModel
        from datagen.strata import StrataGenerator

        self.physics = PhysicalModel(self.config)
        self.strata = StrataGenerator(self.config, physics=self.physics, rng=self.physics.rng)
        self.imperfections = ImperfectionInjector(self.config, rng=self.physics.rng)

    @property
    def parameter_count(self) -> int:
        """Total number of tracked generator parameters."""
        return len(self._manifest)

    def manifest(self) -> dict[str, Any]:
        """Return provenance audit summary for manifest.json and dataset profile."""
        counts = {p.value: 0 for p in ProvenanceTag}
        for entry in self._manifest:
            prov = entry["provenance"]
            counts[prov] = counts.get(prov, 0) + 1

        return {
            "total_parameters": len(self._manifest),
            "provenance_breakdown": counts,
            "seed": self.config.seed,
            "profile": self.config.profile,
            "parameters": self._manifest,
        }

    def generate(
        self,
        output_dir: Path | str = "data/generated",
        reports_dir: Path | str = "reports",
        seed: int | None = None,
    ) -> Any:
        """Run the full generator pipeline and emit all required parquet artifacts (T-206).

        Emits:
          - screening.parquet, truth.parquet, full.parquet
          - train.parquet, calib.parquet, test.parquet
          - manifest.json, SPLIT_AUDIT.json
        """
        from datagen.artifacts import generate_dataset

        return generate_dataset(
            config=self.config,
            output_dir=output_dir,
            reports_dir=reports_dir,
            seed=seed,
        )
