"""Realistic data imperfection injection (Phase 2, T-204).

Implements deliberate real-world imperfections specified in DATASET_SPEC.md § 8:
  1. Missing read-point rows (1.5% default) — exercises FR-103 and INSUFFICIENT_DATA path.
  2. BELOW_LOD censored readings (0.5% of leakage rows) — retained, not coerced to 0 (FR-107).
  3. OVERRANGE readings (0.2% default) — retained as overrange, not coerced to limits (FR-107).
  4. Duplicate (part, param, hours) rows (0.3% default) — tests duplicate detection (FR-103).
  5. Unit inconsistency (mA where uA expected, 2 lots default) — tests unit validation (FR-108).
  6. Timestamp jitter / mild non-monotonicity (1.0% default) — tests ordering robustness (FR-103).
  7. Measurement System Analysis (MSA) noise — Gage R&R repeatability & reproducibility
     (operator/tester/socket) with heteroscedastic scaling (D-I-03, D-CD-04).

Invariants:
  - DR-01: Synthetic dataset generated by seeded, specified generator.
  - DR-03: Every generator parameter carries a provenance tag (TEST-GEN-001).
  - DR-09: data_provenance is always "SYNTHETIC" (TEST-PROV-004).
  - DR-10: Generator cannot import model code (backend/core/**).
  - FR-103: Detect missing read-points, duplicates, timestamp jitter.
  - FR-107: Censored readings (<LOD, OVERRANGE) retained as first-class, never coerced to 0.
  - FR-108: Unit mismatches rejected, never silently rescaled.
"""

from __future__ import annotations

from dataclasses import asdict, dataclass
from datetime import UTC, datetime, timedelta
from typing import TYPE_CHECKING, Any

import numpy as np

from datagen.config.schema import (
    DatagenConfig,
    MeasurementStatus,
    ParameterLimitConfig,
    ParameterName,
    default_parameter_limits,
)

if TYPE_CHECKING:
    from datagen.strata import StratifiedLot, StratumPart

# =============================================================================
# 1. Measurement Record (DATASET_SPEC.md § 5.1)
# =============================================================================


@dataclass
class MeasurementRecord:
    """A single row in the long-format measurements table (DATASET_SPEC.md § 5.1)."""

    component_id: str
    lot_id: str
    component_type: str
    parameter: str
    elapsed_hours: int
    measurement_value: float
    measurement_unit: str
    status: str = MeasurementStatus.OK.value
    temperature_c: float = 125.0
    voltage_v: float = 3.3
    read_timestamp: str = "2026-09-01T08:00:00Z"
    absolute_limit_low: float | None = None
    absolute_limit_high: float | None = None
    board_id: str = "BRD-01"
    socket_id: str = "SOCK-01"
    thermal_zone: str = "ZONE-1"
    tester_id: str = "TESTER-01"
    operator_id: str = "OP-01"
    data_provenance: str = "SYNTHETIC"  # Fixed constant per DR-09 / INV-3
    ingest_id: str = "ING-2026-001"
    is_duplicate: bool = False

    def to_dict(self) -> dict[str, Any]:
        """Convert to dictionary for serialization."""
        d = asdict(self)
        # Internal flag not part of emitted schema
        d.pop("is_duplicate", None)
        return d

    @property
    def is_censored(self) -> bool:
        """True if reading is censored (BELOW_LOD or OVERRANGE)."""
        return self.status in (MeasurementStatus.BELOW_LOD.value, MeasurementStatus.OVERRANGE.value)

    @property
    def is_below_lod(self) -> bool:
        """True if reading is below limit of detection."""
        return self.status == MeasurementStatus.BELOW_LOD.value

    @property
    def is_overrange(self) -> bool:
        """True if reading exceeded instrument measurement range."""
        return self.status == MeasurementStatus.OVERRANGE.value


# =============================================================================
# 2. Record Conversion Helpers
# =============================================================================


def convert_part_to_records(
    part: StratumPart,
    limits: dict[str, ParameterLimitConfig] | None = None,
    start_time: datetime | None = None,
    voltage: float = 3.3,
    board_id: str = "BRD-01",
    tester_id: str = "TESTER-01",
    operator_id: str = "OP-01",
    ingest_id: str = "ING-2026-001",
) -> list[MeasurementRecord]:
    """Convert a StratumPart into raw measurement records across all parameters and read-points."""
    p_limits = limits if limits is not None else default_parameter_limits()
    t_start = start_time if start_time is not None else datetime(2026, 9, 1, 8, 0, tzinfo=UTC)

    records: list[MeasurementRecord] = []
    zone_name = getattr(part.trajectory, "thermal_zone_id", None) or (
        part.trajectory.thermal_zone.zone_id
        if hasattr(part.trajectory, "thermal_zone") and part.trajectory.thermal_zone
        else "ZONE-1"
    )
    actual_temps = getattr(part.trajectory, "actual_temperatures_c", {})

    for param, pt_dict in part.values.items():
        limit_cfg = p_limits.get(param)
        unit = limit_cfg.unit if limit_cfg else "uA"
        abs_min = limit_cfg.absolute_min if limit_cfg else None
        abs_max = limit_cfg.absolute_max if limit_cfg else None

        for t, val in sorted(pt_dict.items()):
            actual_temp = actual_temps.get(t, 125.0)
            read_time = t_start + timedelta(hours=t)

            records.append(
                MeasurementRecord(
                    component_id=part.component_id,
                    lot_id=part.lot_id,
                    component_type=part.component_type.value,
                    parameter=param,
                    elapsed_hours=t,
                    measurement_value=float(val),
                    measurement_unit=unit,
                    status=MeasurementStatus.OK.value,
                    temperature_c=float(actual_temp),
                    voltage_v=voltage,
                    read_timestamp=read_time.isoformat(),
                    absolute_limit_low=abs_min,
                    absolute_limit_high=abs_max,
                    board_id=board_id,
                    socket_id=part.socket_id,
                    thermal_zone=zone_name,
                    tester_id=tester_id,
                    operator_id=operator_id,
                    data_provenance="SYNTHETIC",
                    ingest_id=ingest_id,
                )
            )

    return records


def convert_lot_to_records(
    lot: StratifiedLot,
    limits: dict[str, ParameterLimitConfig] | None = None,
    start_time: datetime | None = None,
    operator_pool: list[str] | None = None,
    tester_pool: list[str] | None = None,
) -> list[MeasurementRecord]:
    """Convert an entire StratifiedLot into measurement records."""
    operators = operator_pool or ["OP-01", "OP-02", "OP-03", "OP-04"]
    testers = tester_pool or ["TESTER-01", "TESTER-02"]

    all_records: list[MeasurementRecord] = []
    for i, part in enumerate(lot.parts):
        op = operators[i % len(operators)]
        tester = testers[i % len(testers)]
        part_records = convert_part_to_records(
            part=part,
            limits=limits,
            start_time=start_time,
            operator_id=op,
            tester_id=tester,
        )
        all_records.extend(part_records)

    return all_records


# =============================================================================
# 3. Individual Imperfection Injectors (T-204)
# =============================================================================


def inject_missing_rows(
    records: list[MeasurementRecord],
    missing_rate: float = 0.015,
    rng: np.random.Generator | None = None,
) -> tuple[list[MeasurementRecord], list[MeasurementRecord]]:
    """Inject missing read-point rows (DATASET_SPEC § 8).

    Exercises FR-103 and the INSUFFICIENT_DATA path.

    Args:
        records: List of measurement records.
        missing_rate: Fraction of rows to drop (default 0.015 = 1.5%).
        rng: Random generator.

    Returns:
        tuple of (retained_records, dropped_records).
    """
    if not records or missing_rate <= 0.0:
        return list(records), []

    generator = rng if rng is not None else np.random.default_rng()
    n = len(records)
    mask = generator.random(n) >= missing_rate

    retained: list[MeasurementRecord] = []
    dropped: list[MeasurementRecord] = []

    for rec, keep in zip(records, mask, strict=True):
        if keep:
            retained.append(rec)
        else:
            dropped.append(rec)

    return retained, dropped


def inject_censoring(
    records: list[MeasurementRecord],
    below_lod_rate: float = 0.005,
    overrange_rate: float = 0.002,
    limits: dict[str, ParameterLimitConfig] | None = None,
    rng: np.random.Generator | None = None,
    lod_thresholds: dict[str, float] | None = None,
    escape_component_ids: set[str] | list[str] | None = None,
) -> list[MeasurementRecord]:
    """Inject BELOW_LOD and OVERRANGE censored readings (DATASET_SPEC § 8, FR-107).

    Guarantees:
      - BELOW_LOD applies strictly to leakage rows (iddq_standby, leakage_input).
      - Censoring is retained as a first-class value, NEVER coerced to 0 or limit.
      - OVERRANGE reading is flagged with OVERRANGE status and set to instrument
        overrange sentinel/saturation value.
      - Escape Set members (S1, S2) are never assigned OVERRANGE (TEST-GEN-004 / DR-04).

    Args:
        records: List of measurement records.
        below_lod_rate: Fraction of leakage rows censored below LOD (default 0.005 = 0.5%).
        overrange_rate: Fraction of all readings exceeding instrument range (default 0.002 = 0.2%).
        limits: Parameter limit configurations.
        rng: Random generator.
        lod_thresholds: Custom LOD values per parameter.
        escape_component_ids: Component IDs in Escape Set to protect from OVERRANGE.

    Returns:
        Modified records with censoring applied.
    """
    if not records:
        return []

    generator = rng if rng is not None else np.random.default_rng()
    p_limits = limits if limits is not None else default_parameter_limits()
    escape_set = set(escape_component_ids) if escape_component_ids else set()

    # Domain default LOD thresholds per parameter
    default_lods: dict[str, float] = {
        ParameterName.IDDQ_STANDBY.value: 0.10,  # 100 nA instrument floor
        ParameterName.LEAKAGE_INPUT.value: 0.05,  # 50 pA instrument floor
    }
    lods = lod_thresholds or default_lods

    modified: list[MeasurementRecord] = []

    for rec in records:
        # Create shallow copy
        new_rec = MeasurementRecord(**asdict(rec))

        # 1. BELOW_LOD for leakage parameters
        is_leakage = rec.parameter in (
            ParameterName.IDDQ_STANDBY.value,
            ParameterName.LEAKAGE_INPUT.value,
        )
        if is_leakage and below_lod_rate > 0.0 and float(generator.random()) < below_lod_rate:
            lod_val = lods.get(rec.parameter, 0.05)
            # Set status to BELOW_LOD; record the LOD limit value, neither 0.0 nor silent (FR-107)
            new_rec.status = MeasurementStatus.BELOW_LOD.value
            new_rec.measurement_value = float(lod_val)
            modified.append(new_rec)
            continue

        # 2. OVERRANGE for all parameters (Escape Set members are excluded per TEST-GEN-004 / DR-04)
        is_escape_part = rec.component_id in escape_set
        if (
            not is_escape_part
            and overrange_rate > 0.0
            and float(generator.random()) < overrange_rate
        ):
            limit_cfg = p_limits.get(rec.parameter)
            abs_max = limit_cfg.absolute_max if limit_cfg and limit_cfg.absolute_max else 100.0
            # Overrange saturated instrument reading (e.g. 1.25x limit, not coerced to limit)
            new_rec.status = MeasurementStatus.OVERRANGE.value
            new_rec.measurement_value = float(abs_max * float(generator.uniform(1.20, 1.40)))
            modified.append(new_rec)
            continue

        modified.append(new_rec)

    return modified


def inject_duplicates(
    records: list[MeasurementRecord],
    duplicate_rate: float = 0.003,
    rng: np.random.Generator | None = None,
) -> list[MeasurementRecord]:
    """Inject duplicate (component_id, parameter, elapsed_hours) rows (DATASET_SPEC § 8).

    Tests FR-103 duplicate detection.

    Args:
        records: List of measurement records.
        duplicate_rate: Fraction of rows to duplicate (default 0.003 = 0.3%).
        rng: Random generator.

    Returns:
        Records containing injected duplicates inserted directly adjacent or at random positions.
    """
    if not records or duplicate_rate <= 0.0:
        return list(records)

    generator = rng if rng is not None else np.random.default_rng()
    result: list[MeasurementRecord] = []

    for rec in records:
        result.append(rec)
        if float(generator.random()) < duplicate_rate:
            # Duplicate row with identical (part, param, hours)
            dup = MeasurementRecord(**asdict(rec))
            dup.is_duplicate = True
            result.append(dup)

    return result


def inject_timestamp_jitter(
    records: list[MeasurementRecord],
    jitter_rate: float = 0.010,
    rng: np.random.Generator | None = None,
    max_jitter_minutes: float = 45.0,
) -> list[MeasurementRecord]:
    """Inject timestamp jitter and mild non-monotonicity (DATASET_SPEC § 8).

    Tests ordering robustness and FR-103 non-monotonic time detection.

    Args:
        records: List of measurement records.
        jitter_rate: Fraction of rows to perturb (default 0.010 = 1.0%).
        rng: Random generator.
        max_jitter_minutes: Maximum perturbation in minutes.

    Returns:
        Records with perturbed timestamps.
    """
    if not records or jitter_rate <= 0.0:
        return list(records)

    generator = rng if rng is not None else np.random.default_rng()
    result: list[MeasurementRecord] = []

    for rec in records:
        new_rec = MeasurementRecord(**asdict(rec))
        if float(generator.random()) < jitter_rate:
            try:
                ts = datetime.fromisoformat(rec.read_timestamp)
                # Perturb backward or forward by up to max_jitter_minutes
                jitter_min = float(generator.uniform(-max_jitter_minutes, max_jitter_minutes))
                perturbed = ts + timedelta(minutes=jitter_min)
                new_rec.read_timestamp = perturbed.isoformat()
            except (ValueError, TypeError):
                pass
        result.append(new_rec)

    return result


def inject_unit_inconsistencies(
    records: list[MeasurementRecord],
    target_lot_ids: set[str] | list[str],
    target_param: str = ParameterName.IDDQ_STANDBY.value,
    original_unit: str = "uA",
    inconsistent_unit: str = "mA",
) -> list[MeasurementRecord]:
    """Inject unit inconsistency on designated lots (DATASET_SPEC § 8, FR-108).

    Emits mA where uA expected for designated lots.
    Guarantees:
      - Unit validation (FR-108) can detect declared unit disagreement with profile.
      - Never silently rescaled.

    Args:
        records: List of measurement records.
        target_lot_ids: Set of lot IDs where unit is corrupted.
        target_param: Parameter to corrupt (default iddq_standby).
        original_unit: Profile unit (default uA).
        inconsistent_unit: Inconsistent unit (default mA).

    Returns:
        Records with unit inconsistency applied to targeted lots.
    """
    target_set = set(target_lot_ids)
    result: list[MeasurementRecord] = []

    for rec in records:
        new_rec = MeasurementRecord(**asdict(rec))
        if rec.lot_id in target_set and rec.parameter == target_param:
            new_rec.measurement_unit = inconsistent_unit
        result.append(new_rec)

    return result


def inject_msa_noise(
    records: list[MeasurementRecord],
    rng: np.random.Generator | None = None,
    repeatability_rel_scale: float = 0.005,
    operator_offsets: dict[str, float] | None = None,
    tester_drift_per_hour: float = 0.0005,
    hetero_exp: float = 0.50,
) -> list[MeasurementRecord]:
    """Inject Measurement System Analysis (MSA) noise components (D-I-03, D-CD-04).

    Decomposes measurement error into standard Gage R&R components:
      1. Equipment Repeatability: Within-gage random noise on every read.
      2. Operator Reproducibility: Operator-specific probe offset (OP-01 vs OP-02).
      3. Tester Drift: Time-dependent instrument calibration drift across read hours.
      4. Heteroscedasticity: Shot-noise scaling proportional to sqrt(value).

    Args:
        records: List of measurement records.
        rng: Random generator.
        repeatability_rel_scale: Relative standard deviation of gage repeatability.
        operator_offsets: Fixed relative bias per operator ID.
        tester_drift_per_hour: Linear tester drift rate per burn-in hour.
        hetero_exp: Heteroscedasticity exponent (default 0.50).

    Returns:
        Records with MSA noise applied.
    """
    if not records:
        return []

    generator = rng if rng is not None else np.random.default_rng()

    # Operator reproducibility offsets (D-I-03: pseudonymous OP-nn)
    op_bias: dict[str, float] = operator_offsets or {
        "OP-01": 0.0,
        "OP-02": 0.008,
        "OP-03": -0.006,
        "OP-04": 0.004,
    }

    result: list[MeasurementRecord] = []

    for rec in records:
        if rec.status != MeasurementStatus.OK.value:
            # Do not corrupt already censored readings
            result.append(rec)
            continue

        new_rec = MeasurementRecord(**asdict(rec))
        val = rec.measurement_value

        # 1. Gage Repeatability (zero-mean equipment noise)
        scale = repeatability_rel_scale * max(abs(val), 0.1)
        if rec.parameter in (ParameterName.IDDQ_STANDBY.value, ParameterName.LEAKAGE_INPUT.value):
            # Heteroscedastic scaling
            scale *= (max(abs(val), 0.1) / 10.0) ** hetero_exp

        repeatability_noise = float(generator.normal(0.0, scale))

        # 2. Operator Reproducibility
        op_offset = op_bias.get(rec.operator_id, 0.0) * val

        # 3. Tester Drift
        drift = tester_drift_per_hour * rec.elapsed_hours * val

        # Rendered MSA measurement
        noisy_val = val + repeatability_noise + op_offset + drift
        if rec.parameter != ParameterName.VTH_SHIFT.value and noisy_val < 0.0:
            noisy_val = max(0.01, val * 0.1)

        new_rec.measurement_value = float(noisy_val)
        result.append(new_rec)

    return result


# =============================================================================
# 4. Master Imperfection Pipeline & Audit Report
# =============================================================================


@dataclass
class ImperfectionResult:
    """Summary of injected realistic imperfections and observed rates."""

    total_initial_records: int
    total_emitted_records: int
    missing_count: int
    missing_rate_observed: float
    below_lod_count: int
    below_lod_rate_observed: float
    overrange_count: int
    overrange_rate_observed: float
    duplicate_count: int
    duplicate_rate_observed: float
    timestamp_jitter_count: int
    timestamp_jitter_rate_observed: float
    unit_inconsistent_lot_count: int
    msa_noise_applied: bool

    def to_dict(self) -> dict[str, Any]:
        """Convert to audit dictionary."""
        return asdict(self)


class ImperfectionInjector:
    """Master orchestrator for injecting realistic data imperfections (T-204).

    Applies the full imperfection stack per DATASET_SPEC § 8:
      - MSA noise (Gage R&R repeatability & reproducibility)
      - BELOW_LOD & OVERRANGE censoring
      - Missing read-point rows
      - Duplicate rows
      - Timestamp jitter
      - Unit inconsistencies
    """

    def __init__(
        self,
        config: DatagenConfig | None = None,
        limits: dict[str, ParameterLimitConfig] | None = None,
        rng: np.random.Generator | None = None,
    ) -> None:
        """Initialize the imperfection injector.

        Args:
            config: Datagen configuration containing imperfection rates.
            limits: Parameter screening limits.
            rng: Random generator.
        """
        self.config = config
        self.limits = limits if limits is not None else default_parameter_limits()
        self.rng = rng if rng is not None else np.random.default_rng(20260930)

        # Extract rates from config or defaults
        if self.config is not None:
            imp = self.config.imperfections
            self.missing_rate = float(imp.missing_rate.value)
            self.below_lod_rate = float(imp.below_lod_rate.value)
            self.overrange_rate = float(imp.overrange_rate.value)
            self.duplicate_rate = float(imp.duplicate_rate.value)
            self.timestamp_jitter_rate = float(imp.timestamp_jitter_rate.value)
        else:
            self.missing_rate = 0.015
            self.below_lod_rate = 0.005
            self.overrange_rate = 0.002
            self.duplicate_rate = 0.003
            self.timestamp_jitter_rate = 0.010

    def apply(
        self,
        records: list[MeasurementRecord],
        unit_mismatch_lots: set[str] | list[str] | None = None,
        apply_msa: bool = True,
        escape_component_ids: set[str] | list[str] | None = None,
    ) -> tuple[list[MeasurementRecord], ImperfectionResult]:
        """Apply all configured imperfections to a list of measurement records.

        Args:
            records: Initial measurement records.
            unit_mismatch_lots: Specific lots to inject unit mismatches into.
            apply_msa: If True, inject MSA repeatability & reproducibility noise.
            escape_component_ids: Specific component IDs belonging to the Escape Set (S1, S2)
                that must never violate absolute screening limits (TEST-GEN-004 / DR-04).

        Returns:
            tuple of (final_emitted_records, imperfection_audit_result).
        """
        initial_count = len(records)
        if initial_count == 0:
            return [], ImperfectionResult(
                total_initial_records=0,
                total_emitted_records=0,
                missing_count=0,
                missing_rate_observed=0.0,
                below_lod_count=0,
                below_lod_rate_observed=0.0,
                overrange_count=0,
                overrange_rate_observed=0.0,
                duplicate_count=0,
                duplicate_rate_observed=0.0,
                timestamp_jitter_count=0,
                timestamp_jitter_rate_observed=0.0,
                unit_inconsistent_lot_count=0,
                msa_noise_applied=False,
            )

        working = list(records)

        # 1. MSA Noise
        if apply_msa:
            working = inject_msa_noise(working, rng=self.rng)

        # 2. Censoring (BELOW_LOD on leakage, OVERRANGE on all except Escape Set)
        leakage_count_before = sum(
            1
            for r in working
            if r.parameter in (ParameterName.IDDQ_STANDBY.value, ParameterName.LEAKAGE_INPUT.value)
        )
        working = inject_censoring(
            records=working,
            below_lod_rate=self.below_lod_rate,
            overrange_rate=self.overrange_rate,
            limits=self.limits,
            rng=self.rng,
            escape_component_ids=escape_component_ids,
        )
        below_lod_count = sum(1 for r in working if r.status == MeasurementStatus.BELOW_LOD.value)
        overrange_count = sum(1 for r in working if r.status == MeasurementStatus.OVERRANGE.value)

        # 3. Missing read-points (drop rows)
        working, dropped = inject_missing_rows(
            records=working,
            missing_rate=self.missing_rate,
            rng=self.rng,
        )
        missing_count = len(dropped)

        # 4. Duplicate rows
        working_before_dups = len(working)
        working = inject_duplicates(
            records=working,
            duplicate_rate=self.duplicate_rate,
            rng=self.rng,
        )
        duplicate_count = sum(1 for r in working if r.is_duplicate)

        # 5. Timestamp jitter
        original_timestamps = [r.read_timestamp for r in working]
        working = inject_timestamp_jitter(
            records=working,
            jitter_rate=self.timestamp_jitter_rate,
            rng=self.rng,
        )
        jitter_count = sum(
            1
            for r, orig_ts in zip(working, original_timestamps, strict=True)
            if r.read_timestamp != orig_ts
        )

        # 6. Unit inconsistency
        mismatch_lots = set(unit_mismatch_lots or [])
        if mismatch_lots:
            working = inject_unit_inconsistencies(
                records=working,
                target_lot_ids=mismatch_lots,
            )

        # Ensure Escape Set members strictly satisfy inside-limits constraint (TEST-GEN-004 / DR-04)
        if escape_component_ids:
            escape_set = set(escape_component_ids)
            for r in working:
                if r.component_id in escape_set:
                    lim = self.limits.get(r.parameter)
                    if lim:
                        if lim.absolute_max is not None and r.measurement_value >= lim.absolute_max:
                            r.measurement_value = float(lim.absolute_max - 0.5)
                        if lim.absolute_min is not None and r.measurement_value <= lim.absolute_min:
                            r.measurement_value = float(lim.absolute_min + 0.5)
                        if r.status == MeasurementStatus.OVERRANGE.value:
                            r.status = MeasurementStatus.OK.value

        # Compile audit statistics
        below_lod_rate_obs = (
            (below_lod_count / leakage_count_before) if leakage_count_before > 0 else 0.0
        )
        overrange_rate_obs = overrange_count / initial_count
        missing_rate_obs = missing_count / (initial_count or 1)
        duplicate_rate_obs = duplicate_count / (working_before_dups or 1)
        jitter_rate_obs = jitter_count / (len(working) or 1)

        result = ImperfectionResult(
            total_initial_records=initial_count,
            total_emitted_records=len(working),
            missing_count=missing_count,
            missing_rate_observed=float(missing_rate_obs),
            below_lod_count=below_lod_count,
            below_lod_rate_observed=float(below_lod_rate_obs),
            overrange_count=overrange_count,
            overrange_rate_observed=float(overrange_rate_obs),
            duplicate_count=duplicate_count,
            duplicate_rate_observed=float(duplicate_rate_obs),
            timestamp_jitter_count=jitter_count,
            timestamp_jitter_rate_observed=float(jitter_rate_obs),
            unit_inconsistent_lot_count=len(mismatch_lots),
            msa_noise_applied=apply_msa,
        )

        return working, result

    def apply_to_lot(
        self,
        lot: StratifiedLot,
        unit_mismatch_lots: set[str] | list[str] | None = None,
        apply_msa: bool = True,
        escape_component_ids: set[str] | list[str] | None = None,
    ) -> tuple[list[MeasurementRecord], ImperfectionResult]:
        """Convert a StratifiedLot to records and apply all imperfections."""
        records = convert_lot_to_records(lot, limits=self.limits)
        escapes = escape_component_ids or {p.component_id for p in lot.parts if p.is_escape}
        return self.apply(
            records=records,
            unit_mismatch_lots=unit_mismatch_lots,
            apply_msa=apply_msa,
            escape_component_ids=escapes,
        )
