"""Ground-truth label and stratum derivation strictly from rendered values (Phase 2, T-205).

Implements the non-negotiable rule defined in DATA_GENERATION_SPEC.md § 4 step 7 and
DECISIONS.md D-014:
  "The generator emits values first; labels are computed FROM THE EMITTED VALUES by applying
   the ground-truth rule to the 168 h column. Intent is retained separately as stratum for
   analysis only, and is never a training target."

Consequences:
  - If random noise pushes an intended defect part inside normal limits and wear-in bounds,
    it is labelled HEALTHY because in this corpus it IS clean on disk.
  - If random noise pushes an intended healthy part outside limits, it is labelled FAILED/S0
    regardless of generator intent.
  - Escape Set (S1 union S2) members are strictly verified: they must be inside absolute
    limits across all read-points and qualify as lot-relative outliers (S1) or accelerated
    drift defects (S2).

Invariants:
  - DR-01: Synthetic dataset generated by seeded, specified generator.
  - DR-04: Escape Set inside-limits constraint enforced (TEST-GEN-004).
  - DR-05: Labels derived from rendered values, not intent (TEST-GEN-005, D-014).
  - DR-10: Generator cannot import model code (backend/core/**).
  - D-015: Decoy strata (S3, S4, S5) derive as HEALTHY and must_flag=False.
"""

from __future__ import annotations

from dataclasses import asdict, dataclass, field
from typing import TYPE_CHECKING, Any

import numpy as np

from datagen.config.schema import (
    FailureLabel,
    ParameterLimitConfig,
    Stratum,
    default_parameter_limits,
)

if TYPE_CHECKING:
    from datagen.imperfections import MeasurementRecord
    from datagen.strata import StratifiedLot, StratumPart

# =============================================================================
# 1. Label Derivation Result Data Structure
# =============================================================================


@dataclass(frozen=True)
class PartLabelResult:
    """Ground truth classification derived strictly from rendered device values."""

    component_id: str
    lot_id: str
    failure_label: FailureLabel
    stratum: Stratum
    degradation_mode: str
    is_escape: bool
    must_flag: bool
    is_inside_limits: bool
    max_drift_168h: float
    max_drift_ratio_168h: float
    is_24h_outlier: bool
    is_lot_shifted: bool
    has_sensor_artefact: bool
    step_failure_detected: bool
    limit_violations: dict[str, list[tuple[int, float, str]]] = field(default_factory=dict)
    details: dict[str, Any] = field(default_factory=dict)

    def to_dict(self) -> dict[str, Any]:
        """Convert result to dictionary."""
        d = asdict(self)
        d["failure_label"] = self.failure_label.value
        d["stratum"] = self.stratum.value
        return d


# =============================================================================
# 2. Physics & Metric Extraction from Rendered Values
# =============================================================================


def check_absolute_limits(
    values: dict[str, dict[int, float]],
    limits: dict[str, ParameterLimitConfig],
) -> tuple[bool, dict[str, list[tuple[int, float, str]]]]:
    """Check whether any rendered reading violates absolute specification limits.

    Args:
        values: Nested dict param -> {t: value}.
        limits: Dict mapping parameter name to limit configuration.

    Returns:
        tuple of (is_inside_limits, violations_dict).
    """
    violations: dict[str, list[tuple[int, float, str]]] = {}

    for param, pt_dict in values.items():
        limit_cfg = limits.get(param)
        if not limit_cfg:
            continue
        abs_max = limit_cfg.absolute_max
        abs_min = limit_cfg.absolute_min
        param_viols: list[tuple[int, float, str]] = []

        for t, val in pt_dict.items():
            if abs_max is not None and val >= abs_max:
                param_viols.append((t, float(val), f">= absolute_max ({abs_max})"))
            if abs_min is not None and val <= abs_min:
                param_viols.append((t, float(val), f"<= absolute_min ({abs_min})"))

        if param_viols:
            violations[param] = param_viols

    return len(violations) == 0, violations


def compute_drift_and_anomaly_metrics(
    values: dict[str, dict[int, float]],
    limits: dict[str, ParameterLimitConfig],
) -> dict[str, Any]:
    """Compute physical drift, step change, and margin metrics from rendered values.

    Args:
        values: Nested dict param -> {t: value}.
        limits: Dict mapping parameter name to limit configuration.

    Returns:
        Dictionary of per-parameter and aggregated summary metrics.
    """
    param_metrics: dict[str, dict[str, float]] = {}
    max_drift_168h = 0.0
    max_drift_ratio = 0.0
    step_jump_detected = False

    for param, pt_dict in values.items():
        if not pt_dict:
            continue

        r_points = sorted(pt_dict.keys())
        v0 = pt_dict.get(0, pt_dict[r_points[0]])
        v24 = pt_dict.get(24, v0)
        v168 = pt_dict.get(168, pt_dict[r_points[-1]])

        delta_24 = v24 - v0
        delta_168 = v168 - v0

        # Available margin from limit configuration
        limit_cfg = limits.get(param)
        abs_max = limit_cfg.absolute_max if limit_cfg and limit_cfg.absolute_max else 100.0
        abs_min = (
            limit_cfg.absolute_min if limit_cfg and limit_cfg.absolute_min is not None else -abs_max
        )
        direction = limit_cfg.degradation_direction if limit_cfg else "increase"

        if direction == "bidirectional":
            margin = max(abs_max - v0, v0 - abs_min, 1.0)
            drift_ratio = abs(delta_168) / margin
        else:
            margin = max(abs_max - v0, 0.5)
            drift_ratio = max(0.0, delta_168) / margin

        # Check for catastrophic step jump between read-points (DATASET_SPEC § 6 sudden_failure)
        limit_span = (abs_max - (abs_min or 0.0)) if abs_max else 50.0
        param_step = False
        for i in range(len(r_points) - 1):
            t_curr = r_points[i]
            t_next = r_points[i + 1]
            val_curr = pt_dict[t_curr]
            val_next = pt_dict[t_next]
            step_delta = abs(val_next - val_curr)

            # Sudden failure: large step change (>= 40% of span) exceeding or crossing limits
            exceeds_limit = (abs_max is not None and val_next >= abs_max) or (
                abs_min is not None and val_next <= abs_min
            )
            if step_delta >= 0.40 * limit_span and exceeds_limit:
                param_step = True
                step_jump_detected = True

        param_metrics[param] = {
            "v0": float(v0),
            "v24": float(v24),
            "v168": float(v168),
            "delta_24": float(delta_24),
            "delta_168": float(delta_168),
            "margin": float(margin),
            "drift_ratio": float(drift_ratio),
            "step_jump": 1.0 if param_step else 0.0,
        }

        if abs(delta_168) > max_drift_168h:
            max_drift_168h = abs(delta_168)
        if drift_ratio > max_drift_ratio:
            max_drift_ratio = drift_ratio

    return {
        "params": param_metrics,
        "max_drift_168h": float(max_drift_168h),
        "max_drift_ratio_168h": float(max_drift_ratio),
        "step_jump_detected": step_jump_detected,
    }


# =============================================================================
# 3. Label & Stratum Derivation strictly from Rendered Values (T-205, D-014)
# =============================================================================


def derive_failure_label(
    values: dict[str, dict[int, float]],
    limits: dict[str, ParameterLimitConfig],
    is_24h_outlier: bool = False,
    is_lot_shifted: bool = False,
    has_sensor_artefact: bool = False,
    drift_defect_threshold: float = 0.55,
) -> FailureLabel:
    """Derive ground-truth FailureLabel strictly from rendered values (DR-05, D-014).

    Decision Logic:
      1. Catastrophic jump detected or catastrophic early breach -> FAILED.
      2. Breached absolute limits via drift -> FAILED / LATENT_DEFECT.
      3. Inside absolute limits:
         - S4 sensor artefact or S5 lot shift -> HEALTHY (benign decoys per D-015).
         - 24h lot-relative outlier -> LATENT_DEFECT (early latent defect, S1).
         - Accelerated drift (drift ratio at 168h >= threshold) -> LATENT_DEFECT (S2).
         - Otherwise -> HEALTHY (normal wear-in or stable).

    Note (D-014):
      If a part was intended to be defective, but random noise kept its drift
      below the threshold and inside limits, it is labelled HEALTHY.

    Args:
        values: Rendered measurement values param -> {t: value}.
        limits: Parameter screening limits.
        is_24h_outlier: True if part is a lot-relative outlier at 24 h.
        is_lot_shifted: True if part belongs to a shifted lot.
        has_sensor_artefact: True if part has a socket/sensor artefact.
        drift_defect_threshold: Fraction of available margin consumed by 168h drift.

    Returns:
        Derived FailureLabel enum.
    """
    inside_limits, violations = check_absolute_limits(values, limits)
    metrics = compute_drift_and_anomaly_metrics(values, limits)

    # 1. Catastrophic step failure
    if metrics["step_jump_detected"]:
        return FailureLabel.FAILED

    # 2. Limit violations
    if not inside_limits:
        # Check if limit was breached early at 0h or 24h
        for viols in violations.values():
            for t_pt, _, _ in viols:
                if t_pt in (0, 24):
                    return FailureLabel.FAILED
        # Drift-driven limit breach at 96h or 168h
        return FailureLabel.LATENT_DEFECT

    # 3. Inside limits: evaluate benign decoys vs latent defects
    if has_sensor_artefact or is_lot_shifted:
        return FailureLabel.HEALTHY

    # Early latent defect: lot-relative outlier at 24h
    if is_24h_outlier:
        return FailureLabel.LATENT_DEFECT

    # Accelerated drift: 168h drift consumed significant fraction of margin
    if metrics["max_drift_ratio_168h"] >= drift_defect_threshold:
        return FailureLabel.LATENT_DEFECT

    # Normal wear-in or stable part
    return FailureLabel.HEALTHY


def derive_stratum(
    values: dict[str, dict[int, float]],
    limits: dict[str, ParameterLimitConfig],
    failure_label: FailureLabel,
    is_24h_outlier: bool = False,
    is_lot_shifted: bool = False,
    has_sensor_artefact: bool = False,
) -> Stratum:
    """Derive difficulty Stratum from rendered values and derived failure label (D-014).

    Guarantees:
      - Any reading breaching an absolute limit is strictly S0_CLEAR_FAIL.
      - Decoys (S3, S4, S5) are inside limits and HEALTHY.
      - Escapes (S1, S2) are inside limits and LATENT_DEFECT.

    Args:
        values: Rendered measurement values param -> {t: value}.
        limits: Parameter screening limits.
        failure_label: Derived failure label.
        is_24h_outlier: True if part is a lot-relative outlier at 24 h.
        is_lot_shifted: True if part belongs to a shifted lot.
        has_sensor_artefact: True if part has a socket/sensor artefact.

    Returns:
        Derived Stratum enum.
    """
    inside_limits, _ = check_absolute_limits(values, limits)

    # Invariant 1: Any absolute limit breach -> S0
    if not inside_limits:
        return Stratum.S0_CLEAR_FAIL

    # Invariant 2: Inside limits healthy parts
    if failure_label == FailureLabel.HEALTHY:
        if is_lot_shifted:
            return Stratum.S5_LOT_SHIFT
        if has_sensor_artefact:
            return Stratum.S4_DECOY_SENSOR
        return Stratum.S3_DECOY_HEALTHY

    # Invariant 3: Inside limits defective parts (Escape Set S1 union S2)
    if is_24h_outlier:
        return Stratum.S1_ESCAPE_ANOMALY
    return Stratum.S2_ESCAPE_DRIFT


def derive_is_escape(
    values: dict[str, dict[int, float]],
    limits: dict[str, ParameterLimitConfig],
    failure_label: FailureLabel,
) -> bool:
    """Derive is_escape flag strictly from rendered values (DATASET_SPEC.md § 7).

    Returns True iff part is defective (LATENT_DEFECT or FAILED) AND inside
    absolute limits across all read-points.
    """
    inside_limits, _ = check_absolute_limits(values, limits)
    is_defective = failure_label in (FailureLabel.LATENT_DEFECT, FailureLabel.FAILED)
    return is_defective and inside_limits


def derive_must_flag(stratum: Stratum) -> bool:
    """Return True if system is expected to flag this stratum as defective (D-015)."""
    return stratum in (
        Stratum.S0_CLEAR_FAIL,
        Stratum.S1_ESCAPE_ANOMALY,
        Stratum.S2_ESCAPE_DRIFT,
    )


def derive_part_labels(
    values: dict[str, dict[int, float]],
    limits: dict[str, ParameterLimitConfig] | None = None,
    component_id: str = "C-TEST-0001",
    lot_id: str = "L-2026-001",
    is_24h_outlier: bool = False,
    is_lot_shifted: bool = False,
    has_sensor_artefact: bool = False,
    drift_defect_threshold: float = 0.55,
) -> PartLabelResult:
    """Derive complete ground truth labels for a single semiconductor part.

    Args:
        values: Rendered values dict param -> {t: value}.
        limits: Parameter screening limits.
        component_id: Component ID.
        lot_id: Lot ID.
        is_24h_outlier: Whether the part is a lot-relative outlier at 24 h.
        is_lot_shifted: Whether part belongs to a shifted lot.
        has_sensor_artefact: Whether part has a sensor artefact.
        drift_defect_threshold: Threshold ratio for accelerated drift.

    Returns:
        PartLabelResult containing all derived labels, stratum, and diagnostics.
    """
    p_limits = limits if limits is not None else default_parameter_limits()
    inside_limits, violations = check_absolute_limits(values, p_limits)
    metrics = compute_drift_and_anomaly_metrics(values, p_limits)

    f_label = derive_failure_label(
        values=values,
        limits=p_limits,
        is_24h_outlier=is_24h_outlier,
        is_lot_shifted=is_lot_shifted,
        has_sensor_artefact=has_sensor_artefact,
        drift_defect_threshold=drift_defect_threshold,
    )

    stratum = derive_stratum(
        values=values,
        limits=p_limits,
        failure_label=f_label,
        is_24h_outlier=is_24h_outlier,
        is_lot_shifted=is_lot_shifted,
        has_sensor_artefact=has_sensor_artefact,
    )

    escape_flag = derive_is_escape(values, p_limits, f_label)
    flag_flag = derive_must_flag(stratum)

    # Determine degradation mode string
    if metrics["step_jump_detected"]:
        deg_mode = "sudden_failure"
    elif not inside_limits:
        deg_mode = (
            "accelerated_drift" if f_label == FailureLabel.LATENT_DEFECT else "sudden_failure"
        )
    elif has_sensor_artefact:
        deg_mode = "sensor_noise_anomaly"
    elif is_lot_shifted:
        deg_mode = "lot_shift"
    elif is_24h_outlier:
        deg_mode = "early_latent_defect"
    elif metrics["max_drift_ratio_168h"] >= drift_defect_threshold:
        deg_mode = "accelerated_drift"
    elif metrics["max_drift_ratio_168h"] >= 0.10:
        deg_mode = "gradual_drift"
    else:
        deg_mode = "healthy_stable"

    return PartLabelResult(
        component_id=component_id,
        lot_id=lot_id,
        failure_label=f_label,
        stratum=stratum,
        degradation_mode=deg_mode,
        is_escape=escape_flag,
        must_flag=flag_flag,
        is_inside_limits=inside_limits,
        max_drift_168h=metrics["max_drift_168h"],
        max_drift_ratio_168h=metrics["max_drift_ratio_168h"],
        is_24h_outlier=is_24h_outlier,
        is_lot_shifted=is_lot_shifted,
        has_sensor_artefact=has_sensor_artefact,
        step_failure_detected=metrics["step_jump_detected"],
        limit_violations=violations,
        details=metrics,
    )


# Alias for backwards compatibility
derive_labels_for_part = derive_part_labels


# =============================================================================
# 4. Lot-Level Cohort Derivation (Leave-No-Trace Intent Independence)
# =============================================================================


def derive_lot_labels(
    parts: list[StratumPart] | dict[str, dict[str, dict[int, float]]],
    limits: dict[str, ParameterLimitConfig] | None = None,
    lot_id: str = "L-2026-001",
    is_lot_shifted: bool = False,
    outlier_z_threshold: float = 3.0,
    drift_defect_threshold: float = 0.55,
) -> dict[str, PartLabelResult]:
    """Derive ground-truth labels for an entire lot using cohort statistics at 24 h.

    Evaluates lot-relative 24h outlierness using robust statistics (median and
    robust sigma = IQR / 1.35) computed purely from the rendered 24h values.

    Args:
        parts: List of StratumPart or dict of part_id -> values.
        limits: Parameter screening limits.
        lot_id: Lot identifier.
        is_lot_shifted: True if lot has a coherent process shift.
        outlier_z_threshold: Robust z-score threshold at 24 h for anomaly.
        drift_defect_threshold: Threshold ratio for accelerated drift.

    Returns:
        Dict mapping component_id to PartLabelResult.
    """
    p_limits = limits if limits is not None else default_parameter_limits()

    # Normalize input into dict of part_id -> values
    parts_map: dict[str, dict[str, dict[int, float]]] = {}
    sensor_artefacts: dict[str, bool] = {}

    if hasattr(parts, "parts") and hasattr(parts, "lot_id"):
        for p in parts.parts:
            parts_map[p.component_id] = p.values
            sensor_artefacts[p.component_id] = getattr(p, "sensor_artefact_magnitude", 0.0) > 0.0
        if lot_id is None:
            lot_id = parts.lot_id  # type: ignore[unreachable]
        is_lot_shifted = getattr(parts, "is_shifted_lot", is_lot_shifted)
    elif isinstance(parts, list):
        for p in parts:
            if hasattr(p, "component_id") and hasattr(p, "values"):
                parts_map[p.component_id] = p.values
                has_sensor_artefact = getattr(p, "sensor_artefact_magnitude", 0.0) > 0.0
                sensor_artefacts[p.component_id] = has_sensor_artefact
            elif isinstance(p, dict):  # type: ignore[unreachable]
                parts_map[p["component_id"]] = p["values"]  # type: ignore[unreachable]
                sensor_artefacts[p["component_id"]] = p.get("sensor_artefact_magnitude", 0.0) > 0.0
    elif isinstance(parts, dict):
        parts_map = parts
        sensor_artefacts = dict.fromkeys(parts_map, False)
    else:
        return {}  # type: ignore[unreachable]

    if not parts_map:
        return {}

    # Extract 24h readings across the lot per parameter
    params_in_lot = sorted({p for v in parts_map.values() for p in v})
    lot_stats_24h: dict[str, tuple[float, float]] = {}

    for param in params_in_lot:
        vals_24 = [
            vals[param][24] for vals in parts_map.values() if param in vals and 24 in vals[param]
        ]
        if len(vals_24) >= 3:
            arr = np.array(vals_24, dtype=float)
            q75, q25 = np.percentile(arr, [75, 25])
            iqr = float(q75 - q25)
            med = float(np.median(arr))
            robust_sigma = (iqr / 1.35) if iqr > 1e-6 else float(np.std(arr) or 1.0)
            lot_stats_24h[param] = (med, max(robust_sigma, 1e-6))
        else:
            lot_stats_24h[param] = (0.0, 1.0)

    # Derive labels for each part in the lot
    results: dict[str, PartLabelResult] = {}

    for comp_id, vals in parts_map.items():
        # Check if 24h reading is a robust outlier on any parameter
        is_outlier = False
        for param, (med, sigma) in lot_stats_24h.items():
            if param in vals and 24 in vals[param]:
                z = abs(vals[param][24] - med) / sigma
                if z >= outlier_z_threshold:
                    is_outlier = True
                    break

        has_artefact = sensor_artefacts.get(comp_id, False)

        part_res = derive_part_labels(
            values=vals,
            limits=p_limits,
            component_id=comp_id,
            lot_id=lot_id,
            is_24h_outlier=is_outlier,
            is_lot_shifted=is_lot_shifted,
            has_sensor_artefact=has_artefact,
            drift_defect_threshold=drift_defect_threshold,
        )
        results[comp_id] = part_res

    return results


# Alias for backwards compatibility
derive_labels_for_lot = derive_lot_labels


# =============================================================================
# 5. Independent Oracle Function (TEST-GEN-005)
# =============================================================================


def recompute_ground_truth_labels(
    data: list[MeasurementRecord] | list[StratumPart] | StratifiedLot | dict[str, Any],
    limits: dict[str, ParameterLimitConfig] | None = None,
) -> dict[str, PartLabelResult]:
    """Recompute every label from emitted values with an independent function (TEST-GEN-005).

    Oracle Requirement:
      Intent flags must not appear in the derivation. Recomputes FailureLabel,
      Stratum, is_escape, and must_flag strictly from the emitted measurements.

    Args:
        data: List of MeasurementRecord, list of StratumPart, StratifiedLot, or nested values.
        limits: Parameter screening limits.

    Returns:
        Dict mapping component_id to PartLabelResult.
    """
    from datagen.imperfections import MeasurementRecord
    from datagen.strata import StratifiedLot, StratumPart

    p_limits = limits if limits is not None else default_parameter_limits()

    # Case A: StratifiedLot
    if isinstance(data, StratifiedLot):
        return derive_lot_labels(
            parts=data.parts,
            limits=p_limits,
            lot_id=data.lot_id,
            is_lot_shifted=data.is_shifted_lot,
        )

    # Case B: List of MeasurementRecord
    if isinstance(data, list) and data and isinstance(data[0], MeasurementRecord):
        # Group records by (lot_id, component_id, parameter, elapsed_hours)
        parts_by_lot: dict[str, dict[str, dict[str, dict[int, float]]]] = {}
        for r in data:
            lot_dict = parts_by_lot.setdefault(r.lot_id, {})
            comp_dict = lot_dict.setdefault(r.component_id, {})
            pt_dict = comp_dict.setdefault(r.parameter, {})
            pt_dict[r.elapsed_hours] = r.measurement_value

        all_results: dict[str, PartLabelResult] = {}
        for l_id, lot_parts in parts_by_lot.items():
            lot_res = derive_lot_labels(parts=lot_parts, limits=p_limits, lot_id=l_id)
            all_results.update(lot_res)
        return all_results

    # Case C: List of StratumPart
    if isinstance(data, list) and data and isinstance(data[0], StratumPart):
        first_lot_id = data[0].lot_id
        is_shifted = getattr(data[0], "lot_shift_applied", False)
        return derive_lot_labels(
            parts=data,
            limits=p_limits,
            lot_id=first_lot_id,
            is_lot_shifted=is_shifted,
        )

    # Case D: Raw dictionary
    if isinstance(data, dict):
        return derive_lot_labels(parts=data, limits=p_limits)

    return {}
