"""Physical model for burn-in degradation and parametric screening (Phase 2, T-202).

Implements the forward physical simulation specified in DATA_GENERATION_SPEC.md § 2, 3, 5, 6:
  value(i,p,t) = mu_lot(p, l(i))                    lot centre (process/lot effect)
               + delta_type(p, tau(i))              type offset
               + b_i(p)                             part-to-part baseline offset
               + A_i(p) * Phi(t ; shape_i) * AF(T, Ea_p) degradation
               + s_socket(p, k(i)) + s_tester(p, m(i), t) setup effects
               + eta(i,p,t)                         measurement noise
               [+ step_i(p,t)]                      sudden-failure step

Owner: Data + ML Engineer (worker-data-ml-engineer)
Charter: Pure numeric core, datagen/**, model artifacts.
Invariants:
  - DR-01: Synthetic dataset generated by seeded, specified generator.
  - DR-03: Every parameter carries a provenance tag (TEST-GEN-001).
  - DR-10: Generator cannot import model code (backend/core/**).
  - INV-08: Reproducibility: same seed => byte-identical values.
"""

from __future__ import annotations

import math
from dataclasses import dataclass
from enum import StrEnum
from typing import ClassVar

import numpy as np

from datagen.config.schema import (
    ComponentType,
    DatagenConfig,
    DegradationClass,
    ParameterLimitConfig,
    ParameterName,
    default_parameter_limits,
)

CELSIUS_TO_KELVIN: float = 273.15


class ShapeFamily(StrEnum):
    """Supported degradation shape families (DATA_GENERATION_SPEC.md § 2, DRIFT_SPEC.md § 4.2)."""

    POWER_LAW = "power_law"
    LOG_TIME = "log_time"
    SATURATING = "saturating"
    LINEAR = "linear"


@dataclass(frozen=True)
class ThermalZone:
    """Thermal zone in the oven with stable offset and Arrhenius coupling."""

    zone_id: str
    offset_c: float
    mean_temp_c: float
    mean_temp_k: float


@dataclass(frozen=True)
class BaselineDraw:
    """Baseline measurement draw at t=0 before degradation onset (v0 draw)."""

    component_id: str
    lot_id: str
    component_type: ComponentType
    v0: dict[str, float]
    factors: dict[str, float]
    is_joint_only: bool
    socket_id: str


@dataclass(frozen=True)
class DegradationTrajectory:
    """Complete multi-readpoint physical trajectory for a single component."""

    component_id: str
    lot_id: str
    component_type: ComponentType
    degradation_class: DegradationClass
    thermal_zone_id: str
    read_points: list[int]
    v0: dict[str, float]
    values: dict[str, dict[int, float]]  # param -> {read_point: value}
    amplitudes: dict[str, float]  # param -> A_i(p)
    shape_exponent: float
    actual_temperatures_c: dict[int, float]  # read_point -> actual temp
    arrhenius_af: dict[str, dict[int, float]]  # param -> {read_point: AF}
    amplitude_clipped: bool = False
    step_applied: bool = False


# =============================================================================
# 1. Arrhenius Acceleration Model
# =============================================================================


class ArrheniusModel:
    """Thermal acceleration model based on the Arrhenius reaction rate equation (D-B-01).

    Formula:
        AF = exp( (Ea / k_B) * (1 / T_ref_k - 1 / T_stress_k) )
    """

    def __init__(self, k_boltzmann_ev_per_k: float, t_ref_c: float) -> None:
        """Initialize Arrhenius acceleration calculator.

        Args:
            k_boltzmann_ev_per_k: Boltzmann constant in eV/K (typically 8.617333262e-5).
            t_ref_c: Reference burn-in temperature in Celsius (typically 125.0 °C).
        """
        if k_boltzmann_ev_per_k <= 0:
            raise ValueError(f"Boltzmann constant must be positive, got {k_boltzmann_ev_per_k}")
        if t_ref_c <= -CELSIUS_TO_KELVIN:
            raise ValueError(f"Reference temperature must be above absolute zero, got {t_ref_c} °C")

        self.k_b = float(k_boltzmann_ev_per_k)
        self.t_ref_c = float(t_ref_c)
        self.t_ref_k = self.t_ref_c + CELSIUS_TO_KELVIN

    def compute_af(self, temp_c: float | np.ndarray, ea_ev: float) -> float | np.ndarray:
        """Compute the Arrhenius Acceleration Factor (AF) relative to reference temperature.

        When temp_c == t_ref_c, AF == 1.0.
        When temp_c > t_ref_c, AF > 1.0 (accelerated degradation).
        When temp_c < t_ref_c, AF < 1.0 (decelerated degradation).

        Args:
            temp_c: Operating or zone temperature in Celsius.
            ea_ev: Activation energy in electron-volts (eV).

        Returns:
            Acceleration factor (dimensionless ratio).
        """
        if ea_ev <= 0:
            raise ValueError(f"Activation energy must be positive, got {ea_ev} eV")

        if isinstance(temp_c, (int, float)):
            if temp_c <= -CELSIUS_TO_KELVIN:
                raise ValueError(
                    f"Temperature must be above absolute zero (-273.15 °C), got {temp_c}"
                )
            t_k = float(temp_c) + CELSIUS_TO_KELVIN
            exponent = (ea_ev / self.k_b) * (1.0 / self.t_ref_k - 1.0 / t_k)
            return float(math.exp(exponent))

        arr = np.asarray(temp_c, dtype=np.float64)
        if np.any(arr <= -CELSIUS_TO_KELVIN):
            raise ValueError("All temperatures must be above absolute zero (-273.15 °C)")
        t_k_arr = arr + CELSIUS_TO_KELVIN
        exp_arr = (ea_ev / self.k_b) * (1.0 / self.t_ref_k - 1.0 / t_k_arr)
        result_arr: np.ndarray = np.exp(exp_arr)
        return result_arr

    def equivalent_field_hours(
        self,
        burn_in_hours: float,
        stress_temp_c: float,
        field_temp_c: float,
        ea_ev: float,
    ) -> float:
        """Convert burn-in stress hours into equivalent operational mission hours (FR-309, D-B-01).

        Formula:
            AF_field = exp( (Ea / k_B) * (1 / T_field_K - 1 / T_stress_K) )
            equiv_hours = burn_in_hours * AF_field
        """
        if burn_in_hours < 0:
            raise ValueError(f"Burn-in hours cannot be negative, got {burn_in_hours}")
        if ea_ev <= 0:
            raise ValueError(f"Activation energy must be positive, got {ea_ev}")
        if stress_temp_c <= -CELSIUS_TO_KELVIN or field_temp_c <= -CELSIUS_TO_KELVIN:
            raise ValueError("Temperatures must be above absolute zero")

        t_stress_k = stress_temp_c + CELSIUS_TO_KELVIN
        t_field_k = field_temp_c + CELSIUS_TO_KELVIN
        exponent = (ea_ev / self.k_b) * (1.0 / t_field_k - 1.0 / t_stress_k)
        af_field = math.exp(exponent)
        return float(burn_in_hours * af_field)


# =============================================================================
# 2. Degradation Shape Functions (Phi_g)
# =============================================================================


class DegradationShapeModel:
    """Degradation shape model normalized so Phi(0) = 0 and Phi(24) = 1.0."""

    def __init__(
        self,
        family: ShapeFamily = ShapeFamily.POWER_LAW,
        default_exponent: float = 0.50,
        time_constant_tau: float = 24.0,
    ) -> None:
        """Initialize shape function model.

        Args:
            family: ShapeFamily (power_law, log_time, saturating, linear).
            default_exponent: Exponent n for power law (sub-linear when n < 1.0).
            time_constant_tau: Time constant tau in hours for log/saturating forms.
        """
        if default_exponent <= 0:
            raise ValueError(f"Shape exponent must be positive, got {default_exponent}")
        if time_constant_tau <= 0:
            raise ValueError(f"Time constant tau must be positive, got {time_constant_tau}")

        self.family = family
        self.default_exponent = float(default_exponent)
        self.tau = float(time_constant_tau)

    def evaluate(
        self,
        t: float | int | np.ndarray,
        exponent: float | None = None,
    ) -> float | np.ndarray:
        """Evaluate normalized degradation shape function Phi(t).

        Invariants:
            Phi(0) == 0.0
            Phi(24) == 1.0
            Sub-linear: for n < 1.0, Phi(168) < 168/24 = 7.0

        Args:
            t: Elapsed hours (>= 0).
            exponent: Optional per-part exponent n (defaults to self.default_exponent).

        Returns:
            Shape multiplier (dimensionless).
        """
        n = self.default_exponent if exponent is None else float(exponent)
        if n <= 0:
            raise ValueError(f"Shape exponent must be positive, got {n}")

        is_scalar = isinstance(t, (int, float))
        arr = np.asarray([t] if is_scalar else t, dtype=np.float64)

        if np.any(arr < 0):
            raise ValueError("Elapsed time t must be non-negative")

        result = np.zeros_like(arr)
        nonzero_mask = arr > 0

        if not np.any(nonzero_mask):
            return 0.0 if is_scalar else result

        t_nz = arr[nonzero_mask]

        if self.family == ShapeFamily.POWER_LAW:
            result[nonzero_mask] = (t_nz / 24.0) ** n
        elif self.family == ShapeFamily.LOG_TIME:
            denom = math.log(1.0 + 24.0 / self.tau)
            result[nonzero_mask] = np.log(1.0 + t_nz / self.tau) / denom
        elif self.family == ShapeFamily.SATURATING:
            denom = 1.0 - math.exp(-24.0 / self.tau)
            result[nonzero_mask] = (1.0 - np.exp(-t_nz / self.tau)) / denom
        elif self.family == ShapeFamily.LINEAR:
            result[nonzero_mask] = t_nz / 24.0
        else:
            raise ValueError(f"Unsupported shape family {self.family}")

        # Strict boundary enforcement: Phi(0) = 0.0, Phi(24) = 1.0 within float precision
        result[arr == 0.0] = 0.0
        result[np.isclose(arr, 24.0)] = 1.0

        return float(result[0]) if is_scalar else result


# =============================================================================
# 3. Factor Model for Correlation Structure
# =============================================================================


class FactorCorrelationModel:
    """Factor model generating realistic multi-parameter correlation (DATA_GENERATION_SPEC § 5).

    Latent factors:
        f_supply, f_threshold, f_package ~ Normal(0, 1) per part
        f_leak_specific ~ Normal(0, 1)

    Loadings:
        iddq      += λ₁ · f_supply
        icc       += λ₂ · f_supply
        leakage   += λ₃ · f_supply + λ₄ · f_leak_specific
        prop_delay+= λ₅ · f_threshold
        vth_shift += λ₆ · f_threshold
        output_res+= λ₇ · f_package
    """

    def __init__(
        self,
        lambda_supply_iddq: float = 0.70,
        lambda_supply_icc: float = 0.75,
        lambda_supply_leakage: float = 0.30,
        lambda_leak_specific: float = 0.60,
        lambda_threshold_delay: float = 0.65,
        lambda_threshold_vth: float = 0.60,
        lambda_package_res: float = 0.80,
    ) -> None:
        self.l_iddq = float(lambda_supply_iddq)
        self.l_icc = float(lambda_supply_icc)
        self.l_leak_sup = float(lambda_supply_leakage)
        self.l_leak_spec = float(lambda_leak_specific)
        self.l_delay = float(lambda_threshold_delay)
        self.l_vth = float(lambda_threshold_vth)
        self.l_res = float(lambda_package_res)

        # Compute idiosyncratic variances so Var(z) = 1.0 for each parameter
        self.eps_iddq = math.sqrt(max(0.0, 1.0 - self.l_iddq**2))
        self.eps_icc = math.sqrt(max(0.0, 1.0 - self.l_icc**2))
        self.eps_leak = math.sqrt(max(0.0, 1.0 - (self.l_leak_sup**2 + self.l_leak_spec**2)))
        self.eps_delay = math.sqrt(max(0.0, 1.0 - self.l_delay**2))
        self.eps_vth = math.sqrt(max(0.0, 1.0 - self.l_vth**2))
        self.eps_res = math.sqrt(max(0.0, 1.0 - self.l_res**2))

    def sample_shocks(
        self,
        rng: np.random.Generator,
        is_joint_only: bool = False,
    ) -> tuple[dict[str, float], dict[str, float]]:
        """Sample standardized correlated parameter shocks z(p) ~ N(0, 1).

        Args:
            rng: Seeded NumPy Generator.
            is_joint_only: If True, inject off-manifold factor shock (DATA_GENERATION_SPEC § 5.1).

        Returns:
            Tuple of (standardized_shocks, latent_factors).
        """
        # Sample latent factors
        f_supply = float(rng.normal(0.0, 1.0))
        f_threshold = float(rng.normal(0.0, 1.0))
        f_package = float(rng.normal(0.0, 1.0))
        f_leak_specific = float(rng.normal(0.0, 1.0))

        if is_joint_only:
            # Joint-only anomaly: break supply relationship by perturbing leak-specific factor
            # keeps marginals inside ~2.5 sigma but moves off-manifold
            f_supply = float(rng.uniform(-0.5, 0.5))
            f_leak_specific = 2.4  # off-manifold leakage path

        # Sample independent idiosyncratic standard normals
        e_iddq = float(rng.normal(0.0, 1.0))
        e_icc = float(rng.normal(0.0, 1.0))
        e_leak = float(rng.normal(0.0, 1.0))
        e_delay = float(rng.normal(0.0, 1.0))
        e_vth = float(rng.normal(0.0, 1.0))
        e_res = float(rng.normal(0.0, 1.0))

        # Combine via factor loadings
        z_iddq = self.l_iddq * f_supply + self.eps_iddq * e_iddq
        z_icc = self.l_icc * f_supply + self.eps_icc * e_icc
        z_leak = (
            self.l_leak_sup * f_supply + self.l_leak_spec * f_leak_specific + self.eps_leak * e_leak
        )
        z_delay = self.l_delay * f_threshold + self.eps_delay * e_delay
        z_vth = self.l_vth * f_threshold + self.eps_vth * e_vth
        z_res = self.l_res * f_package + self.eps_res * e_res

        shocks = {
            ParameterName.IDDQ_STANDBY.value: z_iddq,
            ParameterName.ICC_ACTIVE.value: z_icc,
            ParameterName.LEAKAGE_INPUT.value: z_leak,
            ParameterName.PROP_DELAY.value: z_delay,
            ParameterName.VTH_SHIFT.value: z_vth,
            ParameterName.OUTPUT_RES.value: z_res,
        }

        factors = {
            "f_supply": f_supply,
            "f_threshold": f_threshold,
            "f_package": f_package,
            "f_leak_specific": f_leak_specific,
        }

        return shocks, factors


# =============================================================================
# 4. Master Physical Model Engine (T-202)
# =============================================================================


class PhysicalModel:
    """Master Physical Model coordinating thermal confound, shape degradation, and baseline draws.

    Fully implements T-202:
      1. Baseline draw (v0) with lot/type effects and right-skewed leakage.
      2. Population and per-part sub-linear degradation shapes (Phi_g).
      3. Per-part degradation amplitude parameterized by class and available margin.
      4. Thermal zone variation and Arrhenius acceleration (thermal confound).
      5. Escape Set inside-limits verification and clipping (DATASET_SPEC § 7.1).
    """

    # Typical within-lot baseline standard deviations (sigma_within)
    DEFAULT_SIGMA_WITHIN: ClassVar[dict[str, float]] = {
        ParameterName.IDDQ_STANDBY.value: 1.0,  # uA
        ParameterName.LEAKAGE_INPUT.value: 0.67,  # nA
        ParameterName.PROP_DELAY.value: 0.67,  # ns
        ParameterName.VTH_SHIFT.value: 2.50,  # mV
        ParameterName.ICC_ACTIVE.value: 1.67,  # mA
        ParameterName.OUTPUT_RES.value: 3.33,  # mOhm
    }

    # Small type-specific nominal offsets to reflect device physics across component types
    TYPE_OFFSETS: ClassVar[dict[ComponentType, dict[str, float]]] = {
        ComponentType.CMOS_LOGIC: {
            ParameterName.IDDQ_STANDBY.value: 0.0,
            ParameterName.LEAKAGE_INPUT.value: 0.0,
            ParameterName.PROP_DELAY.value: 0.0,
            ParameterName.VTH_SHIFT.value: 0.0,
            ParameterName.ICC_ACTIVE.value: 0.0,
            ParameterName.OUTPUT_RES.value: 0.0,
        },
        ComponentType.SRAM: {
            ParameterName.IDDQ_STANDBY.value: 1.0,
            ParameterName.LEAKAGE_INPUT.value: 0.5,
            ParameterName.PROP_DELAY.value: -0.5,
            ParameterName.VTH_SHIFT.value: 0.0,
            ParameterName.ICC_ACTIVE.value: 2.0,
            ParameterName.OUTPUT_RES.value: -5.0,
        },
        ComponentType.LDO_REG: {
            ParameterName.IDDQ_STANDBY.value: -1.0,
            ParameterName.LEAKAGE_INPUT.value: -0.5,
            ParameterName.PROP_DELAY.value: 1.0,
            ParameterName.VTH_SHIFT.value: 0.0,
            ParameterName.ICC_ACTIVE.value: -2.0,
            ParameterName.OUTPUT_RES.value: 2.0,
        },
        ComponentType.OPAMP: {
            ParameterName.IDDQ_STANDBY.value: -0.5,
            ParameterName.LEAKAGE_INPUT.value: -0.2,
            ParameterName.PROP_DELAY.value: 1.5,
            ParameterName.VTH_SHIFT.value: 0.5,
            ParameterName.ICC_ACTIVE.value: -3.0,
            ParameterName.OUTPUT_RES.value: 5.0,
        },
        ComponentType.POWER_MOSFET: {
            ParameterName.IDDQ_STANDBY.value: 2.0,
            ParameterName.LEAKAGE_INPUT.value: 1.0,
            ParameterName.PROP_DELAY.value: 0.5,
            ParameterName.VTH_SHIFT.value: -0.5,
            ParameterName.ICC_ACTIVE.value: 3.0,
            ParameterName.OUTPUT_RES.value: 8.0,
        },
    }

    def __init__(
        self,
        config: DatagenConfig,
        rng: np.random.Generator | None = None,
    ) -> None:
        """Initialize Physical Model with strictly validated DatagenConfig.

        Args:
            config: DatagenConfig holding all tagged parameters.
            rng: Optional NumPy Generator (defaults to PCG64 seeded with config.seed).
        """
        self.config = config
        self.rng = np.random.default_rng(config.seed) if rng is None else rng

        # 1. Physics & Arrhenius
        self.arrhenius = ArrheniusModel(
            k_boltzmann_ev_per_k=float(config.physics.k_boltzmann_ev_per_k.value),
            t_ref_c=float(config.physics.t_ref_c.value),
        )

        # 2. Degradation shape
        self.shape_model = DegradationShapeModel(
            family=ShapeFamily.POWER_LAW,
            default_exponent=float(config.degradation.shape_exponent_mean.value),
        )

        # 3. Factor correlation model
        self.factor_model = FactorCorrelationModel(
            lambda_supply_iddq=float(config.factors.lambda_supply_iddq.value),
            lambda_supply_icc=float(config.factors.lambda_supply_icc.value),
            lambda_supply_leakage=float(config.factors.lambda_supply_leakage.value),
            lambda_leak_specific=float(config.factors.lambda_leak_specific.value),
            lambda_threshold_delay=float(config.factors.lambda_threshold_delay.value),
            lambda_threshold_vth=float(config.factors.lambda_threshold_vth.value),
            lambda_package_res=float(config.factors.lambda_package_res.value),
        )

        # 4. Activation energies per parameter
        self.ea_ev = {param: float(tagged.value) for param, tagged in config.physics.ea_ev.items()}

        # 5. Process nominals & limits
        self.nominals = {
            ParameterName.IDDQ_STANDBY.value: float(config.process.iddq_nominal.value),
            ParameterName.LEAKAGE_INPUT.value: float(config.process.leakage_nominal.value),
            ParameterName.PROP_DELAY.value: float(config.process.prop_delay_nominal.value),
            ParameterName.VTH_SHIFT.value: float(config.process.vth_shift_nominal.value),
            ParameterName.ICC_ACTIVE.value: float(config.process.icc_nominal.value),
            ParameterName.OUTPUT_RES.value: float(config.process.output_res_nominal.value),
        }

        # Load default profile limits
        self.limits: dict[str, ParameterLimitConfig] = default_parameter_limits()

        # 6. Initialize thermal zones
        self.thermal_zones = self._init_thermal_zones()

    def _init_thermal_zones(self, n_zones: int = 4) -> dict[str, ThermalZone]:
        """Initialize oven thermal zones with stable Gaussian offsets (DATA_GENERATION_SPEC § 6)."""
        zones: dict[str, ThermalZone] = {}
        setpoint = float(self.config.temperature.setpoint_c.value)
        std = float(self.config.temperature.zone_offset_std_c.value)
        clip = float(self.config.temperature.zone_offset_clip_c.value)

        # Deterministically spaced offsets across chamber zones to guarantee realistic coverage
        for i in range(n_zones):
            zone_id = f"ZONE_{i+1}"
            raw_offset = float(self.rng.normal(0.0, std))
            offset = float(np.clip(raw_offset, -clip, clip))
            mean_c = setpoint + offset
            zones[zone_id] = ThermalZone(
                zone_id=zone_id,
                offset_c=offset,
                mean_temp_c=mean_c,
                mean_temp_k=mean_c + CELSIUS_TO_KELVIN,
            )
        return zones

    def draw_lot_centres(
        self,
        lot_id: str,
        component_type: ComponentType | str = ComponentType.CMOS_LOGIC,
    ) -> dict[str, float]:
        """Draw lot-level baseline centres mu_lot(p) ~ Normal(mu_nominal, sigma_lot).

        Args:
            lot_id: Lot identifier string (e.g. 'L-2026-001').
            component_type: Target ComponentType enum or string.

        Returns:
            Dict mapping parameter name to lot centre value.
        """
        c_type = (
            component_type
            if isinstance(component_type, ComponentType)
            else ComponentType(component_type)
        )
        type_offsets = self.TYPE_OFFSETS.get(c_type, {})
        ratio = float(self.config.process.sigma_lot_ratio.value)

        centres: dict[str, float] = {}
        for param, nominal in self.nominals.items():
            sigma_w = self.DEFAULT_SIGMA_WITHIN.get(param, 1.0)
            sigma_lot = ratio * sigma_w
            delta_t = type_offsets.get(param, 0.0)
            lot_mean = float(self.rng.normal(nominal + delta_t, sigma_lot))
            # Keep lot mean physically valid
            if param in (
                ParameterName.IDDQ_STANDBY.value,
                ParameterName.LEAKAGE_INPUT.value,
                ParameterName.PROP_DELAY.value,
                ParameterName.ICC_ACTIVE.value,
                ParameterName.OUTPUT_RES.value,
            ):
                lot_mean = max(lot_mean, nominal * 0.5)
            centres[param] = lot_mean

        return centres

    def draw_v0(
        self,
        component_id: str,
        lot_id: str,
        component_type: ComponentType | str = ComponentType.CMOS_LOGIC,
        lot_centre: dict[str, float] | None = None,
        degradation_class: DegradationClass | str = DegradationClass.HEALTHY_STABLE,
        is_joint_only: bool = False,
        socket_id: str = "SOCK-01",
    ) -> BaselineDraw:
        """Draw un-degraded t=0 baseline readings (v0 draw).

        Implements:
            v0(i,p) = μ_lot(p) + b_i(p) + s_socket(p) + η(i,p,0)

        Args:
            component_id: Unique part ID.
            lot_id: Lot ID.
            component_type: Semiconductor type.
            lot_centre: Optional precomputed lot centres.
            degradation_class: Target degradation class.
            is_joint_only: If True, inject joint-only factor anomaly.
            socket_id: Burn-in socket ID.

        Returns:
            BaselineDraw instance with v0 readings and latent state.
        """
        c_type = (
            component_type
            if isinstance(component_type, ComponentType)
            else ComponentType(component_type)
        )
        d_class = (
            degradation_class
            if isinstance(degradation_class, DegradationClass)
            else DegradationClass(degradation_class)
        )

        centres = self.draw_lot_centres(lot_id, c_type) if lot_centre is None else lot_centre
        shocks, factors = self.factor_model.sample_shocks(self.rng, is_joint_only=is_joint_only)

        socket_scale = float(self.config.setup_effects.socket_offset_scale.value)
        meas_noise_scale = float(self.config.setup_effects.measurement_noise_scale.value)
        hetero_exp = float(self.config.setup_effects.heteroscedasticity_exponent.value)

        v0_values: dict[str, float] = {}

        for param, mu_lot in centres.items():
            sigma_w = self.DEFAULT_SIGMA_WITHIN.get(param, 1.0)
            z = shocks[param]

            # Part-to-part baseline offset b_i(p)
            if param in (ParameterName.IDDQ_STANDBY.value, ParameterName.LEAKAGE_INPUT.value):
                # Right-skewed LogNormal distribution for leakage (D-B-04)
                s = 0.45
                b_i = (
                    sigma_w
                    * (math.exp(s * z) - math.exp(0.5 * s**2))
                    / math.sqrt(math.exp(s**2) - 1.0)
                )
            else:
                # Symmetric Normal for delay, vth_shift, icc, output_res
                b_i = sigma_w * z

            # Early latent defect baseline elevation (outlier from 0h, inside absolute limits)
            if d_class == DegradationClass.EARLY_LATENT_DEFECT:
                if param == ParameterName.IDDQ_STANDBY.value:
                    b_i += 3.2 * sigma_w
                elif param == ParameterName.LEAKAGE_INPUT.value and not is_joint_only:
                    b_i += 2.8 * sigma_w

            # Socket contact resistance effect s_socket
            s_socket = float(self.rng.normal(0.0, socket_scale * sigma_w))

            # Base value before measurement noise
            val = mu_lot + b_i + s_socket

            # Measurement noise η(0) with heteroscedastic scaling for leakage
            sigma_meas = meas_noise_scale * sigma_w
            if param in (ParameterName.IDDQ_STANDBY.value, ParameterName.LEAKAGE_INPUT.value):
                scale = (max(0.1, val) / max(0.1, mu_lot)) ** hetero_exp
                sigma_meas *= scale

            # 3x noise for HEALTHY_NOISY class
            if d_class == DegradationClass.HEALTHY_NOISY:
                sigma_meas *= 3.0

            eta = float(self.rng.normal(0.0, sigma_meas))
            final_v0 = val + eta

            # Physical non-negativity constraint for unipolar parameters
            if param in (
                ParameterName.IDDQ_STANDBY.value,
                ParameterName.LEAKAGE_INPUT.value,
                ParameterName.PROP_DELAY.value,
                ParameterName.ICC_ACTIVE.value,
                ParameterName.OUTPUT_RES.value,
            ):
                final_v0 = max(final_v0, 0.05 * mu_lot)

            v0_values[param] = final_v0

        return BaselineDraw(
            component_id=component_id,
            lot_id=lot_id,
            component_type=c_type,
            v0=v0_values,
            factors=factors,
            is_joint_only=is_joint_only,
            socket_id=socket_id,
        )

    def draw_amplitudes(
        self,
        v0: dict[str, float],
        degradation_class: DegradationClass | str = DegradationClass.HEALTHY_STABLE,
    ) -> dict[str, float]:
        """Draw per-part degradation amplitude A_i(p) for all measured parameters.

        The amplitude corresponds to degradation rate at 24 h at reference temperature.
        It is scaled to available margin M(p) = absolute_max(p) - v0(p).

        Args:
            v0: Baseline readings dictionary.
            degradation_class: Ground truth degradation class.

        Returns:
            Dict mapping parameter name to amplitude A_i(p).
        """
        d_class = (
            degradation_class
            if isinstance(degradation_class, DegradationClass)
            else DegradationClass(degradation_class)
        )

        amplitudes: dict[str, float] = {}

        h_amp = float(self.config.degradation.healthy_amplitude.value)
        g_amp = float(self.config.degradation.gradual_drift_amplitude.value)
        acc_amp = float(self.config.degradation.accelerated_drift_amplitude.value)
        eld_amp = float(self.config.degradation.early_latent_defect_amplitude.value)

        for param, val in v0.items():
            limit_cfg = self.limits.get(param)
            abs_max = (
                limit_cfg.absolute_max
                if (limit_cfg is not None and limit_cfg.absolute_max is not None)
                else 100.0
            )
            abs_min = (
                limit_cfg.absolute_min
                if (limit_cfg is not None and limit_cfg.absolute_min is not None)
                else -abs_max
            )
            direction = limit_cfg.degradation_direction if limit_cfg else "increase"

            # Available margin
            if direction == "bidirectional":
                # For vth_shift, randomly choose positive or negative drift
                sign = 1.0 if self.rng.uniform(0.0, 1.0) >= 0.5 else -1.0
                margin = (abs_max - val) if sign > 0 else (val - abs_min)
            else:
                sign = 1.0
                margin = max(0.5, abs_max - val)

            # Amplitude fraction based on degradation class
            if d_class in (
                DegradationClass.HEALTHY_STABLE,
                DegradationClass.HEALTHY_NOISY,
                DegradationClass.SENSOR_NOISE_ANOMALY,
                DegradationClass.LOT_SHIFT,
            ):
                frac = h_amp * float(self.rng.uniform(0.5, 1.5))
            elif d_class == DegradationClass.GRADUAL_DRIFT:
                frac = g_amp * float(self.rng.uniform(0.8, 1.2))
            elif d_class == DegradationClass.ACCELERATED_DRIFT:
                frac = acc_amp * float(self.rng.uniform(0.9, 1.3))
            elif d_class == DegradationClass.EARLY_LATENT_DEFECT:
                frac = eld_amp * float(self.rng.uniform(0.8, 1.2))
            elif d_class == DegradationClass.SUDDEN_FAILURE:
                frac = g_amp * float(self.rng.uniform(0.8, 1.2))
            else:
                # INTERMITTENT or other residual class
                frac = eld_amp * float(self.rng.uniform(0.7, 1.3))

            amplitudes[param] = sign * frac * margin

        return amplitudes

    def simulate_trajectory(
        self,
        v0: BaselineDraw | dict[str, float],
        degradation_class: DegradationClass | str = DegradationClass.HEALTHY_STABLE,
        thermal_zone: ThermalZone | None = None,
        read_points: list[int] | None = None,
        shape_exponent: float | None = None,
        enforce_inside_limits: bool = False,
        component_id: str = "C-TEST-0001",
        lot_id: str = "L-2026-001",
        component_type: ComponentType | str = ComponentType.CMOS_LOGIC,
    ) -> DegradationTrajectory:
        """Simulate physical degradation across all read-points.

        Implements:
            value(i,p,t) = v0(i,p)
                         + A_i(p) · Φ(t) · AF(T_zone(t), Ea_p)
                         + s_tester(p, t)
                         + η(i,p,t)
                         [+ step_i(t)]

        Args:
            v0: BaselineDraw or v0 values dict.
            degradation_class: Ground truth behaviour class.
            thermal_zone: Oven thermal zone (defaults to ZONE_1).
            read_points: List of read-points in hours (defaults to [0, 24, 96, 168]).
            shape_exponent: Per-part shape exponent n (drawn from normal if None).
            enforce_inside_limits: If True, rejection-sample and clip for Escape Set S1/S2.
            component_id: Component ID.
            lot_id: Lot ID.
            component_type: Component type.

        Returns:
            DegradationTrajectory holding values across all read-points.
        """
        c_id = v0.component_id if isinstance(v0, BaselineDraw) else component_id
        l_id = v0.lot_id if isinstance(v0, BaselineDraw) else lot_id
        c_type = (
            v0.component_type
            if isinstance(v0, BaselineDraw)
            else (
                component_type
                if isinstance(component_type, ComponentType)
                else ComponentType(component_type)
            )
        )
        v0_dict = v0.v0 if isinstance(v0, BaselineDraw) else v0

        d_class = (
            degradation_class
            if isinstance(degradation_class, DegradationClass)
            else DegradationClass(degradation_class)
        )

        zone = self.thermal_zones["ZONE_1"] if thermal_zone is None else thermal_zone
        r_points = [0, 24, 96, 168] if read_points is None else sorted(read_points)

        # Draw per-part shape exponent n_i ~ Normal(mean, spread), clipped to sub-linear range
        if shape_exponent is None:
            n_mean = float(self.config.degradation.shape_exponent_mean.value)
            n_spread = float(self.config.degradation.shape_exponent_spread.value)
            n_i = float(np.clip(self.rng.normal(n_mean, n_spread), 0.15, 0.95))
        else:
            n_i = float(shape_exponent)

        amplitudes = self.draw_amplitudes(v0_dict, d_class)

        # Generate thermocouple read jitter per read-point
        jitter_std = float(self.config.temperature.jitter_std_c.value)
        actual_temps: dict[int, float] = {}
        for t in r_points:
            jitter = float(self.rng.normal(0.0, jitter_std))
            actual_temps[t] = zone.mean_temp_c + jitter

        # Precompute Arrhenius AF per parameter and read-point
        af_matrix: dict[str, dict[int, float]] = {}
        for param in v0_dict:
            ea = self.ea_ev.get(param, 0.7)
            af_matrix[param] = {}
            for t in r_points:
                af_val = float(self.arrhenius.compute_af(actual_temps[t], ea))
                af_matrix[param][t] = af_val

        # Setup effects & measurement noise parameters
        tester_slope = float(self.config.setup_effects.tester_drift_slope.value)
        meas_noise_scale = float(self.config.setup_effects.measurement_noise_scale.value)
        hetero_exp = float(self.config.setup_effects.heteroscedasticity_exponent.value)

        # Sudden failure step injection at t >= 96h
        step_applied = False
        step_mult = float(self.config.degradation.sudden_failure_step.value)

        # Render trajectory values
        values: dict[str, dict[int, float]] = {p: {} for p in v0_dict}
        clipped = False

        for param, initial_v0 in v0_dict.items():
            sigma_w = self.DEFAULT_SIGMA_WITHIN.get(param, 1.0)
            amp = amplitudes[param]

            for t in r_points:
                if t == 0:
                    # At t=0, drift is 0; value is v0
                    values[param][0] = initial_v0
                    continue

                # Degradation term: A * Phi(t) * AF
                phi_t = float(self.shape_model.evaluate(t, exponent=n_i))
                af_t = af_matrix[param][t]
                degradation = amp * phi_t * af_t

                # Equipment linear drift
                s_tester = tester_slope * t

                # Measurement noise
                sigma_meas = meas_noise_scale * sigma_w
                if param in (ParameterName.IDDQ_STANDBY.value, ParameterName.LEAKAGE_INPUT.value):
                    sigma_meas *= (max(0.1, initial_v0) / 10.0) ** hetero_exp

                if d_class == DegradationClass.HEALTHY_NOISY:
                    sigma_meas *= 3.0

                eta = float(self.rng.normal(0.0, sigma_meas))

                rendered_val = initial_v0 + degradation + s_tester + eta

                # Sudden failure jump step at t >= 96h
                if d_class == DegradationClass.SUDDEN_FAILURE and t >= 96:
                    rendered_val *= step_mult
                    step_applied = True

                # Keep physical floor
                if param != ParameterName.VTH_SHIFT.value:
                    rendered_val = max(rendered_val, 0.05 * initial_v0)

                values[param][t] = rendered_val

        # Escape Set Constraint Enforcement (DATASET_SPEC § 7.1)
        if enforce_inside_limits:
            values, amplitudes, clipped = self._enforce_escape_limits(
                values=values,
                v0_dict=v0_dict,
                amplitudes=amplitudes,
                r_points=r_points,
                n_i=n_i,
                af_matrix=af_matrix,
                tester_slope=tester_slope,
            )

        return DegradationTrajectory(
            component_id=c_id,
            lot_id=l_id,
            component_type=c_type,
            degradation_class=d_class,
            thermal_zone_id=zone.zone_id,
            read_points=r_points,
            v0=v0_dict,
            values=values,
            amplitudes=amplitudes,
            shape_exponent=n_i,
            actual_temperatures_c=actual_temps,
            arrhenius_af=af_matrix,
            amplitude_clipped=clipped,
            step_applied=step_applied,
        )

    def _enforce_escape_limits(
        self,
        values: dict[str, dict[int, float]],
        v0_dict: dict[str, float],
        amplitudes: dict[str, float],
        r_points: list[int],
        n_i: float,
        af_matrix: dict[str, dict[int, float]],
        tester_slope: float,
    ) -> tuple[dict[str, dict[int, float]], dict[str, float], bool]:
        """Enforce strict inside-limits constraint for Escape Set S1 and S2 (DATASET_SPEC § 7.1).

        Guarantees that for every parameter and read-point:
            limit_low(p) < value(part, p, t) < limit_high(p)
        """
        clipped = False

        for param in v0_dict:
            limit_cfg = self.limits.get(param)
            if not limit_cfg:
                continue

            abs_max = limit_cfg.absolute_max
            abs_min = limit_cfg.absolute_min

            # Check if any read-point violates limits
            violates = False
            for t in r_points:
                val = values[param][t]
                if abs_max is not None and val >= abs_max:
                    violates = True
                    break
                if abs_min is not None and val <= abs_min:
                    violates = True
                    break

            if not violates:
                continue

            # Constraint violated: scale down amplitude analytically to guarantee clearance
            # target max reading at (limit - 5% safety margin)
            clipped = True
            init_v0 = v0_dict[param]

            if abs_max is not None and values[param][168] >= abs_max:
                target_168 = abs_max - 0.05 * (abs_max - init_v0)
                phi_168 = float(self.shape_model.evaluate(168, exponent=n_i))
                af_168 = af_matrix[param][168]
                denom = max(1e-6, phi_168 * af_168)
                new_amp = (target_168 - init_v0 - tester_slope * 168) / denom
                amplitudes[param] = max(0.01 * amplitudes[param], new_amp)

            elif abs_min is not None and values[param][168] <= abs_min:
                target_168 = abs_min + 0.05 * (init_v0 - abs_min)
                phi_168 = float(self.shape_model.evaluate(168, exponent=n_i))
                af_168 = af_matrix[param][168]
                denom = max(1e-6, phi_168 * af_168)
                new_amp = (target_168 - init_v0 - tester_slope * 168) / denom
                amplitudes[param] = min(-0.01 * abs(amplitudes[param]), new_amp)

            # Re-render values with adjusted amplitude
            for t in r_points:
                if t == 0:
                    continue
                phi_t = float(self.shape_model.evaluate(t, exponent=n_i))
                af_t = af_matrix[param][t]
                new_val = init_v0 + amplitudes[param] * phi_t * af_t + tester_slope * t
                # Ensure strictly inside
                if abs_max is not None:
                    new_val = min(new_val, abs_max - 0.5)
                if abs_min is not None:
                    new_val = max(new_val, abs_min + 0.5)
                values[param][t] = new_val

        return values, amplitudes, clipped
