"""Difficulty strata S0-S5 and decoy generation logic (Phase 2, T-203).

Implements the difficulty strata S0-S5, Escape Set (S1 union S2), and benign decoy
behaviour defined in DATASET_SPEC.md § 6, 7 and DATA_GENERATION_SPEC.md § 4, 5.1, 7.1:

  Stratum S0-clear-fail:
    Exceeds an absolute limit at some read-point. Catastrophic failures, large
    step changes (sudden failure), or uncontained drift. Ground truth: FAILED
    or LATENT_DEFECT. Static limit screening catches these.

  Stratum S1-escape-anomaly (Module A flagship target):
    Inside absolute limits at ALL read-points {0, 24, 96, 168} h, but a
    lot-relative outlier at 24 h. Generated from early_latent_defect
    (elevated baseline) or off-manifold joint_only factor anomalies.
    Ground truth: LATENT_DEFECT. is_escape: True.

  Stratum S2-escape-drift (Module B flagship target):
    Inside absolute limits at ALL read-points {0, 24, 96, 168} h, lot-relative
    NORMAL at 24 h, but unsafe projected trajectory / large amplitude drift
    by 168 h. Generated from accelerated_drift with strictly enforced
    inside-limits constraint. Ground truth: LATENT_DEFECT. is_escape: True.

  Stratum S3-decoy-healthy (Decoy: FP pressure):
    Healthy part that sits high in its lot by chance, has elevated measurement
    noise (healthy_noisy 3x), or exhibits normal gradual wear-in drift.
    Ground truth: HEALTHY. Must NOT be flagged as defective / rejected.

  Stratum S4-decoy-sensor (Decoy: attribution target):
    Part is physically healthy, but a measurement/setup artefact corrupts
    the sensor or socket readings (sensor_artefact_magnitude > 0).
    Ground truth: HEALTHY. Must NOT be rejected; must be attributed to
    socket/sensor for retest (RETEST_DIFFERENT_SOCKET per FR-407).

  Stratum S5-lot-shift (Decoy: DPAT vs SPAT test):
    Whole lot mean is shifted coherently (e.g., +2.5 to +3.5 sigma_w), but
    parts are internally consistent and healthy. All parts remain inside
    absolute limits. Ground truth: HEALTHY. DPAT absorbs the shift, so the
    lot passes and parts are not flagged.

Invariants:
  - DR-01: Synthetic dataset generated by seeded, specified generator.
  - DR-03: Every generator parameter carries a provenance tag (TEST-GEN-001).
  - DR-04: Escape Set (S1 union S2) non-empty; ALL members inside ALL limits (TEST-GEN-004).
  - DR-05: Labels derived from rendered values, not intent (TEST-GEN-005, D-014).
  - DR-10: Generator cannot import model code (backend/core/**).
  - D-015: Decoy strata (S3, S4, S5) must NOT be flagged as defective.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import ClassVar

import numpy as np

from datagen.config.schema import (
    ComponentType,
    DatagenConfig,
    DegradationClass,
    FailureLabel,
    ParameterLimitConfig,
    ParameterName,
    Stratum,
    default_parameter_limits,
)
from datagen.physics import (
    DegradationTrajectory,
    PhysicalModel,
    ThermalZone,
)

# =============================================================================
# 1. Stratum Groups and Predicates
# =============================================================================

DECOY_STRATA: frozenset[Stratum] = frozenset(
    {
        Stratum.S3_DECOY_HEALTHY,
        Stratum.S4_DECOY_SENSOR,
        Stratum.S5_LOT_SHIFT,
    }
)

ESCAPE_STRATA: frozenset[Stratum] = frozenset(
    {
        Stratum.S1_ESCAPE_ANOMALY,
        Stratum.S2_ESCAPE_DRIFT,
    }
)

FLAGGED_TARGET_STRATA: frozenset[Stratum] = frozenset(
    {
        Stratum.S0_CLEAR_FAIL,
        Stratum.S1_ESCAPE_ANOMALY,
        Stratum.S2_ESCAPE_DRIFT,
    }
)


def is_decoy(stratum: Stratum | str) -> bool:
    """Return True if stratum is an adversarial decoy that must NOT be flagged (D-015)."""
    s = stratum if isinstance(stratum, Stratum) else Stratum(stratum)
    return s in DECOY_STRATA


def is_escape(stratum: Stratum | str) -> bool:
    """Return True if stratum belongs to the Escape Set S1 union S2 (DATASET_SPEC § 7)."""
    s = stratum if isinstance(stratum, Stratum) else Stratum(stratum)
    return s in ESCAPE_STRATA


def must_flag(stratum: Stratum | str) -> bool:
    """Return True if system is expected to flag this stratum as defective (False for decoys)."""
    s = stratum if isinstance(stratum, Stratum) else Stratum(stratum)
    return s in FLAGGED_TARGET_STRATA


# =============================================================================
# 2. Stratum Record Data Structures
# =============================================================================


@dataclass(frozen=True)
class StratumPart:
    """A generated semiconductor part with full trajectory and stratum context."""

    component_id: str
    lot_id: str
    component_type: ComponentType
    stratum: Stratum
    degradation_class: DegradationClass
    failure_label: FailureLabel
    is_escape: bool
    is_decoy: bool
    values: dict[str, dict[int, float]]  # param -> {t: value}
    trajectory: DegradationTrajectory
    sensor_artefact_magnitude: float = 0.0
    is_joint_only: bool = False
    amplitude_clipped: bool = False
    lot_shift_applied: bool = False
    socket_id: str = "SOCK-01"

    @property
    def value_0h(self) -> dict[str, float]:
        """Values at 0 h read-point."""
        return {p: self.values[p].get(0, 0.0) for p in self.values}

    @property
    def value_24h(self) -> dict[str, float]:
        """Values at 24 h read-point."""
        return {p: self.values[p].get(24, 0.0) for p in self.values}

    @property
    def value_96h(self) -> dict[str, float]:
        """Values at 96 h read-point."""
        return {p: self.values[p].get(96, 0.0) for p in self.values}

    @property
    def value_168h(self) -> dict[str, float]:
        """Values at 168 h read-point."""
        return {p: self.values[p].get(168, 0.0) for p in self.values}


@dataclass(frozen=True)
class StratifiedLot:
    """An entire lot of parts with stratum distributions and process metadata."""

    lot_id: str
    component_type: ComponentType
    parts: list[StratumPart]
    lot_centre: dict[str, float]
    is_shifted_lot: bool = False
    shift_magnitude: float = 0.0

    @property
    def count(self) -> int:
        """Total parts in the lot."""
        return len(self.parts)

    @property
    def stratum_counts(self) -> dict[str, int]:
        """Count of parts per stratum in this lot."""
        counts = {s.value: 0 for s in Stratum}
        for p in self.parts:
            counts[p.stratum.value] += 1
        return counts

    @property
    def escape_count(self) -> int:
        """Count of Escape Set (S1 union S2) parts in this lot."""
        return sum(1 for p in self.parts if p.is_escape)

    @property
    def decoy_count(self) -> int:
        """Count of decoy parts (S3, S4, S5) in this lot."""
        return sum(1 for p in self.parts if p.is_decoy)


# =============================================================================
# 3. Limit Verification & Rendered Classification
# =============================================================================


def check_values_inside_limits(
    values: dict[str, dict[int, float]],
    limits: dict[str, ParameterLimitConfig],
) -> bool:
    """Verify that all readings across all parameters and read-points satisfy absolute limits.

    Constraint (DATASET_SPEC § 7.1):
        limit_low(p) < value(part, p, t) < limit_high(p) for all p, t.

    Args:
        values: Nested dict param -> {t: value}.
        limits: Dict mapping parameter name to limit configuration.

    Returns:
        True if all readings are strictly inside limits; False otherwise.
    """
    for param, pt_dict in values.items():
        limit_cfg = limits.get(param)
        if not limit_cfg:
            continue
        abs_max = limit_cfg.absolute_max
        abs_min = limit_cfg.absolute_min
        for val in pt_dict.values():
            if abs_max is not None and val >= abs_max:
                return False
            if abs_min is not None and val <= abs_min:
                return False
    return True


def find_limit_violations(
    values: dict[str, dict[int, float]],
    limits: dict[str, ParameterLimitConfig],
) -> dict[str, list[tuple[int, float, str]]]:
    """Find and return all absolute limit violations across parameters and read-points.

    Args:
        values: Nested dict param -> {t: value}.
        limits: Dict mapping parameter name to limit configuration.

    Returns:
        Dict mapping parameter to list of (read_point, value, violation_description).
    """
    violations: dict[str, list[tuple[int, float, str]]] = {}
    for param, pt_dict in values.items():
        limit_cfg = limits.get(param)
        if not limit_cfg:
            continue
        abs_max = limit_cfg.absolute_max
        abs_min = limit_cfg.absolute_min
        param_viol: list[tuple[int, float, str]] = []
        for t, val in pt_dict.items():
            if abs_max is not None and val >= abs_max:
                param_viol.append((t, val, f">= absolute_max ({abs_max})"))
            if abs_min is not None and val <= abs_min:
                param_viol.append((t, val, f"<= absolute_min ({abs_min})"))
        if param_viol:
            violations[param] = param_viol
    return violations


def classify_rendered_stratum(
    values: dict[str, dict[int, float]],
    failure_label: FailureLabel,
    limits: dict[str, ParameterLimitConfig],
    is_lot_shifted: bool = False,
    sensor_artefact_magnitude: float = 0.0,
    is_24h_outlier: bool = False,
) -> Stratum:
    """Derive stratum from rendered values (DATA_GENERATION_SPEC § 4 step 7, D-014).

    Implements the non-negotiable rule that stratum is derived from what was
    actually rendered on disk, never from generator intent:
      1. If any rendered value breaches an absolute limit at any read-point,
         it is strictly S0-clear-fail regardless of what was intended.
      2. If all values are inside limits:
         - HEALTHY parts:
           - S5-lot-shift if from a shifted lot.
           - S4-decoy-sensor if sensor artefact magnitude > 0.
           - S3-decoy-healthy otherwise.
         - DEFECTIVE parts:
           - S1-escape-anomaly if lot-relative outlier at 24 h.
           - S2-escape-drift if lot-relative normal at 24 h.

    Args:
        values: Rendered values dictionary.
        failure_label: Ground-truth failure label.
        limits: Parameter limit configurations.
        is_lot_shifted: True if part belongs to a shifted lot.
        sensor_artefact_magnitude: Magnitude of sensor artefact (> 0 only for S4).
        is_24h_outlier: True if part is a lot-relative outlier at 24 h.

    Returns:
        Derived Stratum enum value.
    """
    # 1. Any absolute limit breach -> S0
    if not check_values_inside_limits(values, limits):
        return Stratum.S0_CLEAR_FAIL

    # 2. Inside limits: evaluate ground truth and features
    if failure_label == FailureLabel.HEALTHY:
        if is_lot_shifted:
            return Stratum.S5_LOT_SHIFT
        if sensor_artefact_magnitude > 0.0:
            return Stratum.S4_DECOY_SENSOR
        return Stratum.S3_DECOY_HEALTHY

    # Defective or Failed but inside limits (e.g. latent defect escape)
    if is_24h_outlier:
        return Stratum.S1_ESCAPE_ANOMALY
    return Stratum.S2_ESCAPE_DRIFT


# =============================================================================
# 4. Master Strata Generator (T-203)
# =============================================================================


class StrataGenerator:
    """Master generator for difficulty strata S0-S5 and benign decoys (T-203).

    Fully coordinates forward simulation for:
      - Stratum S0: Clear absolute-limit failures (sudden failure, uncontained drift).
      - Stratum S1: Early latent defect escapes (elevated baseline or joint-only anomaly).
      - Stratum S2: Accelerated drift escapes (normal at 24 h, unsafe 168 h drift, inside limits).
      - Stratum S3: Decoy healthy (sits high by chance or high measurement noise; must not flag).
      - Stratum S4: Decoy sensor artefact (healthy part with setup offset; must not reject).
      - Stratum S5: Decoy lot shift (coherently shifted lot; must not fail lot).
    """

    DEFAULT_SIGMA_WITHIN: ClassVar[dict[str, float]] = {
        ParameterName.IDDQ_STANDBY.value: 1.0,  # uA
        ParameterName.LEAKAGE_INPUT.value: 0.67,  # nA
        ParameterName.PROP_DELAY.value: 0.67,  # ns
        ParameterName.VTH_SHIFT.value: 2.50,  # mV
        ParameterName.ICC_ACTIVE.value: 1.67,  # mA
        ParameterName.OUTPUT_RES.value: 3.33,  # mOhm
    }

    def __init__(
        self,
        config: DatagenConfig,
        physics: PhysicalModel | None = None,
        rng: np.random.Generator | None = None,
    ) -> None:
        """Initialize StrataGenerator with configuration and physical model.

        Args:
            config: Validated DatagenConfig instance.
            physics: Optional pre-instantiated PhysicalModel.
            rng: Optional NumPy Generator (defaults to seeded Generator from config).
        """
        self.config = config
        self.rng = np.random.default_rng(config.seed) if rng is None else rng
        self.physics = PhysicalModel(self.config, rng=self.rng) if physics is None else physics
        self.limits = default_parameter_limits()

    # -------------------------------------------------------------------------
    # Stratum S0: Clear Fail
    # -------------------------------------------------------------------------

    def generate_s0_clear_fail(
        self,
        component_id: str,
        lot_id: str,
        component_type: ComponentType | str = ComponentType.CMOS_LOGIC,
        mechanism: str = "sudden_failure",
        lot_centre: dict[str, float] | None = None,
        thermal_zone: ThermalZone | None = None,
        socket_id: str = "SOCK-01",
    ) -> StratumPart:
        """Generate a Stratum S0 clear-fail part that exceeds absolute limits.

        Args:
            component_id: Unique part ID.
            lot_id: Lot ID.
            component_type: Semiconductor device type.
            mechanism: 'sudden_failure' (multiplicative step jump) or 'accelerated_drift'.
            lot_centre: Optional precomputed lot centres.
            thermal_zone: Oven thermal zone.
            socket_id: Socket identifier.

        Returns:
            StratumPart with S0 stratum and verified limit breach.
        """
        c_type = (
            component_type
            if isinstance(component_type, ComponentType)
            else ComponentType(component_type)
        )
        centres = (
            self.physics.draw_lot_centres(lot_id, c_type) if lot_centre is None else lot_centre
        )

        if mechanism == "sudden_failure":
            d_class = DegradationClass.SUDDEN_FAILURE
            f_label = FailureLabel.FAILED
        else:
            d_class = DegradationClass.ACCELERATED_DRIFT
            f_label = FailureLabel.LATENT_DEFECT

        v0 = self.physics.draw_v0(
            component_id=component_id,
            lot_id=lot_id,
            component_type=c_type,
            lot_centre=centres,
            degradation_class=d_class,
            socket_id=socket_id,
        )

        # Simulate trajectory WITHOUT inside-limits constraint
        traj = self.physics.simulate_trajectory(
            v0=v0,
            degradation_class=d_class,
            thermal_zone=thermal_zone,
            enforce_inside_limits=False,
            component_id=component_id,
            lot_id=lot_id,
            component_type=c_type,
        )

        rendered_values = {p: dict(traj.values[p]) for p in traj.values}

        # Guaranteed invariant: S0 MUST violate an absolute limit at some read-point
        if check_values_inside_limits(rendered_values, self.limits):
            # If step didn't push it over limit due to low baseline, force limit breach at 168h
            target_param = ParameterName.IDDQ_STANDBY.value
            limit_cfg = self.limits[target_param]
            abs_max = limit_cfg.absolute_max if limit_cfg.absolute_max is not None else 50.0
            rendered_values[target_param][168] = abs_max * float(self.rng.uniform(1.15, 1.40))

        return StratumPart(
            component_id=component_id,
            lot_id=lot_id,
            component_type=c_type,
            stratum=Stratum.S0_CLEAR_FAIL,
            degradation_class=d_class,
            failure_label=f_label,
            is_escape=False,
            is_decoy=False,
            values=rendered_values,
            trajectory=traj,
            sensor_artefact_magnitude=0.0,
            is_joint_only=False,
            amplitude_clipped=traj.amplitude_clipped,
            lot_shift_applied=False,
            socket_id=socket_id,
        )

    # -------------------------------------------------------------------------
    # Stratum S1: Escape Anomaly (Module A Flagship Target)
    # -------------------------------------------------------------------------

    def generate_s1_escape_anomaly(
        self,
        component_id: str,
        lot_id: str,
        component_type: ComponentType | str = ComponentType.CMOS_LOGIC,
        is_joint_only: bool = False,
        lot_centre: dict[str, float] | None = None,
        thermal_zone: ThermalZone | None = None,
        socket_id: str = "SOCK-01",
    ) -> StratumPart:
        """Generate a Stratum S1 escape anomaly part (Module A target).

        Inside absolute limits at ALL read-points, but a lot-relative outlier at 24 h.

        Args:
            component_id: Unique part ID.
            lot_id: Lot ID.
            component_type: Semiconductor device type.
            is_joint_only: If True, generate joint-only factor anomaly (DATA_GENERATION_SPEC § 5.1).
            lot_centre: Optional lot centres.
            thermal_zone: Oven thermal zone.
            socket_id: Socket identifier.

        Returns:
            StratumPart with S1 stratum and verified inside-limits invariant (DR-04).
        """
        c_type = (
            component_type
            if isinstance(component_type, ComponentType)
            else ComponentType(component_type)
        )
        centres = (
            self.physics.draw_lot_centres(lot_id, c_type) if lot_centre is None else lot_centre
        )

        d_class = DegradationClass.EARLY_LATENT_DEFECT
        f_label = FailureLabel.LATENT_DEFECT

        v0 = self.physics.draw_v0(
            component_id=component_id,
            lot_id=lot_id,
            component_type=c_type,
            lot_centre=centres,
            degradation_class=d_class,
            is_joint_only=is_joint_only,
            socket_id=socket_id,
        )

        # Strictly enforce inside-limits constraint (DATASET_SPEC § 7.1)
        traj = self.physics.simulate_trajectory(
            v0=v0,
            degradation_class=d_class,
            thermal_zone=thermal_zone,
            enforce_inside_limits=True,
            component_id=component_id,
            lot_id=lot_id,
            component_type=c_type,
        )

        rendered_values = {p: dict(traj.values[p]) for p in traj.values}

        # Strict safety guard: Guarantee zero limit violations across all parameters
        for param, pt_dict in rendered_values.items():
            limit_cfg = self.limits.get(param)
            if not limit_cfg:
                continue
            abs_max = limit_cfg.absolute_max
            abs_min = limit_cfg.absolute_min
            for t in pt_dict:
                val = pt_dict[t]
                if abs_max is not None and val >= abs_max:
                    pt_dict[t] = abs_max - 0.5
                if abs_min is not None and val <= abs_min:
                    pt_dict[t] = abs_min + 0.5

        return StratumPart(
            component_id=component_id,
            lot_id=lot_id,
            component_type=c_type,
            stratum=Stratum.S1_ESCAPE_ANOMALY,
            degradation_class=d_class,
            failure_label=f_label,
            is_escape=True,
            is_decoy=False,
            values=rendered_values,
            trajectory=traj,
            sensor_artefact_magnitude=0.0,
            is_joint_only=is_joint_only,
            amplitude_clipped=traj.amplitude_clipped,
            lot_shift_applied=False,
            socket_id=socket_id,
        )

    # -------------------------------------------------------------------------
    # Stratum S2: Escape Drift (Module B Flagship Target)
    # -------------------------------------------------------------------------

    def generate_s2_escape_drift(
        self,
        component_id: str,
        lot_id: str,
        component_type: ComponentType | str = ComponentType.CMOS_LOGIC,
        lot_centre: dict[str, float] | None = None,
        thermal_zone: ThermalZone | None = None,
        socket_id: str = "SOCK-01",
    ) -> StratumPart:
        """Generate a Stratum S2 escape drift part (Module B target).

        Inside absolute limits at ALL read-points, lot-relative NORMAL at 24 h,
        but unsafe trajectory with large degradation rate by 168 h.

        Args:
            component_id: Unique part ID.
            lot_id: Lot ID.
            component_type: Semiconductor device type.
            lot_centre: Optional lot centres.
            thermal_zone: Oven thermal zone.
            socket_id: Socket identifier.

        Returns:
            StratumPart with S2 stratum, normal at 24h, unsafe at 168h, inside limits.
        """
        c_type = (
            component_type
            if isinstance(component_type, ComponentType)
            else ComponentType(component_type)
        )
        centres = (
            self.physics.draw_lot_centres(lot_id, c_type) if lot_centre is None else lot_centre
        )

        d_class = DegradationClass.ACCELERATED_DRIFT
        f_label = FailureLabel.LATENT_DEFECT

        # Draw baseline without early elevation so part is lot-relative normal at 0h and 24h
        v0 = self.physics.draw_v0(
            component_id=component_id,
            lot_id=lot_id,
            component_type=c_type,
            lot_centre=centres,
            degradation_class=DegradationClass.HEALTHY_STABLE,
            socket_id=socket_id,
        )

        # Enforce inside limits constraint so it remains inside absolute limits at 168h
        traj = self.physics.simulate_trajectory(
            v0=v0,
            degradation_class=d_class,
            thermal_zone=thermal_zone,
            enforce_inside_limits=True,
            component_id=component_id,
            lot_id=lot_id,
            component_type=c_type,
        )

        rendered_values = {p: dict(traj.values[p]) for p in traj.values}

        # Strict safety guard: Guarantee zero limit violations
        for param, pt_dict in rendered_values.items():
            limit_cfg = self.limits.get(param)
            if not limit_cfg:
                continue
            abs_max = limit_cfg.absolute_max
            abs_min = limit_cfg.absolute_min
            for t in pt_dict:
                val = pt_dict[t]
                if abs_max is not None and val >= abs_max:
                    pt_dict[t] = abs_max - 0.5
                if abs_min is not None and val <= abs_min:
                    pt_dict[t] = abs_min + 0.5

        return StratumPart(
            component_id=component_id,
            lot_id=lot_id,
            component_type=c_type,
            stratum=Stratum.S2_ESCAPE_DRIFT,
            degradation_class=d_class,
            failure_label=f_label,
            is_escape=True,
            is_decoy=False,
            values=rendered_values,
            trajectory=traj,
            sensor_artefact_magnitude=0.0,
            is_joint_only=False,
            amplitude_clipped=traj.amplitude_clipped,
            lot_shift_applied=False,
            socket_id=socket_id,
        )

    # -------------------------------------------------------------------------
    # Stratum S3: Decoy Healthy (False-Positive Pressure)
    # -------------------------------------------------------------------------

    def generate_s3_decoy_healthy(
        self,
        component_id: str,
        lot_id: str,
        component_type: ComponentType | str = ComponentType.CMOS_LOGIC,
        variant: str = "noisy",
        lot_centre: dict[str, float] | None = None,
        thermal_zone: ThermalZone | None = None,
        socket_id: str = "SOCK-01",
    ) -> StratumPart:
        """Generate a Stratum S3 decoy healthy part (must NOT be flagged).

        Healthy part that sits high in its lot by chance, has 3x measurement noise,
        or undergoes normal gradual wear-in drift.

        Args:
            component_id: Unique part ID.
            lot_id: Lot ID.
            component_type: Semiconductor device type.
            variant: 'noisy' (3x noise), 'gradual_drift' (normal wear-in), or 'upper_tail'.
            lot_centre: Optional lot centres.
            thermal_zone: Oven thermal zone.
            socket_id: Socket identifier.

        Returns:
            StratumPart with S3 stratum, healthy ground truth, inside limits.
        """
        c_type = (
            component_type
            if isinstance(component_type, ComponentType)
            else ComponentType(component_type)
        )
        centres = (
            self.physics.draw_lot_centres(lot_id, c_type) if lot_centre is None else lot_centre
        )

        if variant == "gradual_drift":
            d_class = DegradationClass.GRADUAL_DRIFT
        elif variant == "noisy":
            d_class = DegradationClass.HEALTHY_NOISY
        else:
            d_class = DegradationClass.HEALTHY_STABLE

        f_label = FailureLabel.HEALTHY

        v0 = self.physics.draw_v0(
            component_id=component_id,
            lot_id=lot_id,
            component_type=c_type,
            lot_centre=centres,
            degradation_class=d_class,
            socket_id=socket_id,
        )

        # Upper tail variant: shift baseline up (1.5 to 2.2 sigma_w) for benign FP pressure
        v0_dict = dict(v0.v0)
        if variant == "upper_tail":
            for param in (
                ParameterName.IDDQ_STANDBY.value,
                ParameterName.PROP_DELAY.value,
            ):
                sigma_w = self.DEFAULT_SIGMA_WITHIN.get(param, 1.0)
                v0_dict[param] += float(self.rng.uniform(1.5, 2.2)) * sigma_w

        traj = self.physics.simulate_trajectory(
            v0=v0_dict,
            degradation_class=d_class,
            thermal_zone=thermal_zone,
            enforce_inside_limits=True,
            component_id=component_id,
            lot_id=lot_id,
            component_type=c_type,
        )

        rendered_values = {p: dict(traj.values[p]) for p in traj.values}

        return StratumPart(
            component_id=component_id,
            lot_id=lot_id,
            component_type=c_type,
            stratum=Stratum.S3_DECOY_HEALTHY,
            degradation_class=d_class,
            failure_label=f_label,
            is_escape=False,
            is_decoy=True,
            values=rendered_values,
            trajectory=traj,
            sensor_artefact_magnitude=0.0,
            is_joint_only=False,
            amplitude_clipped=traj.amplitude_clipped,
            lot_shift_applied=False,
            socket_id=socket_id,
        )

    # -------------------------------------------------------------------------
    # Stratum S4: Decoy Sensor / Socket Artefact (Must Not Be Rejected)
    # -------------------------------------------------------------------------

    def generate_s4_decoy_sensor(
        self,
        component_id: str,
        lot_id: str,
        component_type: ComponentType | str = ComponentType.CMOS_LOGIC,
        artefact_magnitude: float | None = None,
        lot_centre: dict[str, float] | None = None,
        thermal_zone: ThermalZone | None = None,
        socket_id: str = "SOCK-BAD-01",
    ) -> StratumPart:
        """Generate a Stratum S4 decoy sensor artefact part.

        Part is physically healthy, but measurement reading carries a setup/socket
        corruption. Must NOT be rejected; must be attributed to socket/sensor for retest.

        Args:
            component_id: Unique part ID.
            lot_id: Lot ID.
            component_type: Semiconductor device type.
            artefact_magnitude: Optional magnitude of sensor offset.
            lot_centre: Optional lot centres.
            thermal_zone: Oven thermal zone.
            socket_id: Socket identifier (attributed setup unit).

        Returns:
            StratumPart with S4 stratum, sensor_artefact_magnitude > 0, healthy ground truth.
        """
        c_type = (
            component_type
            if isinstance(component_type, ComponentType)
            else ComponentType(component_type)
        )
        centres = (
            self.physics.draw_lot_centres(lot_id, c_type) if lot_centre is None else lot_centre
        )

        d_class = DegradationClass.SENSOR_NOISE_ANOMALY
        f_label = FailureLabel.HEALTHY

        # Underlying physical device is completely healthy
        v0 = self.physics.draw_v0(
            component_id=component_id,
            lot_id=lot_id,
            component_type=c_type,
            lot_centre=centres,
            degradation_class=DegradationClass.HEALTHY_STABLE,
            socket_id=socket_id,
        )

        traj = self.physics.simulate_trajectory(
            v0=v0,
            degradation_class=DegradationClass.HEALTHY_STABLE,
            thermal_zone=thermal_zone,
            enforce_inside_limits=True,
            component_id=component_id,
            lot_id=lot_id,
            component_type=c_type,
        )

        # Inject socket/sensor measurement corruption
        target_param = ParameterName.IDDQ_STANDBY.value
        sigma_w = self.DEFAULT_SIGMA_WITHIN.get(target_param, 1.0)
        mag = (
            float(self.rng.uniform(3.0, 5.5) * sigma_w)
            if artefact_magnitude is None
            else float(artefact_magnitude)
        )

        rendered_values = {p: dict(traj.values[p]) for p in traj.values}
        limit_max = self.limits[target_param].absolute_max or 50.0

        for t in rendered_values[target_param]:
            # Apply additive corruption onto read values for the affected socket
            corrupted = rendered_values[target_param][t] + mag
            # Guarantee reading stays inside absolute limits so it remains S4 decoy, not S0
            rendered_values[target_param][t] = min(corrupted, limit_max - 1.0)

        return StratumPart(
            component_id=component_id,
            lot_id=lot_id,
            component_type=c_type,
            stratum=Stratum.S4_DECOY_SENSOR,
            degradation_class=d_class,
            failure_label=f_label,
            is_escape=False,
            is_decoy=True,
            values=rendered_values,
            trajectory=traj,
            sensor_artefact_magnitude=mag,
            is_joint_only=False,
            amplitude_clipped=traj.amplitude_clipped,
            lot_shift_applied=False,
            socket_id=socket_id,
        )

    # -------------------------------------------------------------------------
    # Stratum S5: Decoy Lot Shift (DPAT Absorbs Shift; Must Not Fail Lot)
    # -------------------------------------------------------------------------

    def generate_s5_lot_shift(
        self,
        component_id: str,
        lot_id: str,
        component_type: ComponentType | str = ComponentType.CMOS_LOGIC,
        shift_sigma_multiplier: float = 2.5,
        lot_centre: dict[str, float] | None = None,
        thermal_zone: ThermalZone | None = None,
        socket_id: str = "SOCK-01",
    ) -> StratumPart:
        """Generate a Stratum S5 decoy lot shift part.

        Part belongs to a coherently shifted lot. Parts inside the lot are internally
        consistent and healthy. DPAT absorbs the shift, so the lot must not fail.

        Args:
            component_id: Unique part ID.
            lot_id: Lot ID.
            component_type: Semiconductor device type.
            shift_sigma_multiplier: Multiplier of sigma_w applied as coherent lot offset.
            lot_centre: Precomputed shifted lot centre.
            thermal_zone: Oven thermal zone.
            socket_id: Socket identifier.

        Returns:
            StratumPart with S5 stratum, healthy ground truth, inside limits.
        """
        c_type = (
            component_type
            if isinstance(component_type, ComponentType)
            else ComponentType(component_type)
        )

        if lot_centre is None:
            base_centres = self.physics.draw_lot_centres(lot_id, c_type)
            centres: dict[str, float] = {}
            for param, mean_val in base_centres.items():
                sigma_w = self.DEFAULT_SIGMA_WITHIN.get(param, 1.0)
                centres[param] = mean_val + shift_sigma_multiplier * sigma_w
        else:
            centres = lot_centre

        d_class = DegradationClass.LOT_SHIFT
        f_label = FailureLabel.HEALTHY

        v0 = self.physics.draw_v0(
            component_id=component_id,
            lot_id=lot_id,
            component_type=c_type,
            lot_centre=centres,
            degradation_class=DegradationClass.HEALTHY_STABLE,
            socket_id=socket_id,
        )

        traj = self.physics.simulate_trajectory(
            v0=v0,
            degradation_class=DegradationClass.HEALTHY_STABLE,
            thermal_zone=thermal_zone,
            enforce_inside_limits=True,
            component_id=component_id,
            lot_id=lot_id,
            component_type=c_type,
        )

        rendered_values = {p: dict(traj.values[p]) for p in traj.values}

        # Keep strictly inside absolute limits
        for param, pt_dict in rendered_values.items():
            limit_cfg = self.limits.get(param)
            if not limit_cfg or limit_cfg.absolute_max is None:
                continue
            for t in pt_dict:
                pt_dict[t] = min(pt_dict[t], limit_cfg.absolute_max - 1.0)

        return StratumPart(
            component_id=component_id,
            lot_id=lot_id,
            component_type=c_type,
            stratum=Stratum.S5_LOT_SHIFT,
            degradation_class=d_class,
            failure_label=f_label,
            is_escape=False,
            is_decoy=True,
            values=rendered_values,
            trajectory=traj,
            sensor_artefact_magnitude=0.0,
            is_joint_only=False,
            amplitude_clipped=traj.amplitude_clipped,
            lot_shift_applied=True,
            socket_id=socket_id,
        )

    # -------------------------------------------------------------------------
    # Dispatcher and Stratified Lot Generator
    # -------------------------------------------------------------------------

    def generate_part_for_stratum(
        self,
        stratum: Stratum | str,
        component_id: str,
        lot_id: str,
        component_type: ComponentType | str = ComponentType.CMOS_LOGIC,
        lot_centre: dict[str, float] | None = None,
        thermal_zone: ThermalZone | None = None,
        socket_id: str = "SOCK-01",
        **kwargs: object,
    ) -> StratumPart:
        """Dispatch part generation for any targeted stratum S0-S5.

        Args:
            stratum: Desired Stratum enum or string.
            component_id: Part ID.
            lot_id: Lot ID.
            component_type: Semiconductor device type.
            lot_centre: Optional lot centres.
            thermal_zone: Oven thermal zone.
            socket_id: Socket identifier.
            **kwargs: Extra parameters (e.g. is_joint_only, variant, artefact_magnitude).

        Returns:
            StratumPart matching the requested stratum.
        """
        s = stratum if isinstance(stratum, Stratum) else Stratum(stratum)

        if s == Stratum.S0_CLEAR_FAIL:
            mech = str(kwargs.get("mechanism", "sudden_failure"))
            return self.generate_s0_clear_fail(
                component_id=component_id,
                lot_id=lot_id,
                component_type=component_type,
                mechanism=mech,
                lot_centre=lot_centre,
                thermal_zone=thermal_zone,
                socket_id=socket_id,
            )
        if s == Stratum.S1_ESCAPE_ANOMALY:
            joint_only = bool(kwargs.get("is_joint_only", False))
            return self.generate_s1_escape_anomaly(
                component_id=component_id,
                lot_id=lot_id,
                component_type=component_type,
                is_joint_only=joint_only,
                lot_centre=lot_centre,
                thermal_zone=thermal_zone,
                socket_id=socket_id,
            )
        if s == Stratum.S2_ESCAPE_DRIFT:
            return self.generate_s2_escape_drift(
                component_id=component_id,
                lot_id=lot_id,
                component_type=component_type,
                lot_centre=lot_centre,
                thermal_zone=thermal_zone,
                socket_id=socket_id,
            )
        if s == Stratum.S3_DECOY_HEALTHY:
            var = str(kwargs.get("variant", "noisy"))
            return self.generate_s3_decoy_healthy(
                component_id=component_id,
                lot_id=lot_id,
                component_type=component_type,
                variant=var,
                lot_centre=lot_centre,
                thermal_zone=thermal_zone,
                socket_id=socket_id,
            )
        if s == Stratum.S4_DECOY_SENSOR:
            mag_val = kwargs.get("artefact_magnitude")
            mag = float(mag_val) if isinstance(mag_val, (int, float)) else None
            return self.generate_s4_decoy_sensor(
                component_id=component_id,
                lot_id=lot_id,
                component_type=component_type,
                artefact_magnitude=mag,
                lot_centre=lot_centre,
                thermal_zone=thermal_zone,
                socket_id=socket_id,
            )
        if s == Stratum.S5_LOT_SHIFT:
            shift_val = kwargs.get("shift_sigma_multiplier", 2.5)
            mult = float(shift_val) if isinstance(shift_val, (int, float)) else 2.5
            return self.generate_s5_lot_shift(
                component_id=component_id,
                lot_id=lot_id,
                component_type=component_type,
                shift_sigma_multiplier=mult,
                lot_centre=lot_centre,
                thermal_zone=thermal_zone,
                socket_id=socket_id,
            )

        raise ValueError(f"Unsupported stratum {s}")

    def generate_stratified_lot(
        self,
        lot_id: str,
        n_parts: int,
        component_type: ComponentType | str = ComponentType.CMOS_LOGIC,
        is_shifted_lot: bool = False,
        thermal_zone: ThermalZone | None = None,
        class_proportions: np.ndarray | None = None,
    ) -> StratifiedLot:
        """Generate an entire lot of parts with configured stratum mixture.

        Args:
            lot_id: Lot ID (e.g. 'L-2026-001').
            n_parts: Total parts to generate in this lot.
            component_type: Semiconductor device type.
            is_shifted_lot: If True, generate an S5 shifted lot.
            thermal_zone: Oven thermal zone.

        Returns:
            StratifiedLot instance containing all generated parts and summary counts.
        """
        c_type = (
            component_type
            if isinstance(component_type, ComponentType)
            else ComponentType(component_type)
        )
        base_centres = self.physics.draw_lot_centres(lot_id, c_type)

        if is_shifted_lot:
            # Shifted lot centre for S5
            shift_mult = 2.8
            shifted_centres: dict[str, float] = {}
            for param, m in base_centres.items():
                sigma_w = self.DEFAULT_SIGMA_WITHIN.get(param, 1.0)
                shifted_centres[param] = m + shift_mult * sigma_w

            parts: list[StratumPart] = []
            for idx in range(n_parts):
                p_id = f"C-{lot_id}-{idx + 1:04d}"
                part = self.generate_s5_lot_shift(
                    component_id=p_id,
                    lot_id=lot_id,
                    component_type=c_type,
                    shift_sigma_multiplier=shift_mult,
                    lot_centre=shifted_centres,
                    thermal_zone=thermal_zone,
                    socket_id=f"SOCK-{(idx % 16) + 1:02d}",
                )
                parts.append(part)

            return StratifiedLot(
                lot_id=lot_id,
                component_type=c_type,
                parts=parts,
                lot_centre=shifted_centres,
                is_shifted_lot=True,
                shift_magnitude=shift_mult,
            )

        # Standard lot: sample classes according to Dirichlet / mixture proportions
        mixture = self.config.class_mixture
        classes = [
            DegradationClass.HEALTHY_STABLE,
            DegradationClass.HEALTHY_NOISY,
            DegradationClass.GRADUAL_DRIFT,
            DegradationClass.ACCELERATED_DRIFT,
            DegradationClass.EARLY_LATENT_DEFECT,
            DegradationClass.SUDDEN_FAILURE,
            DegradationClass.SENSOR_NOISE_ANOMALY,
        ]
        if class_proportions is not None:
            proportions = np.asarray(class_proportions, dtype=float)
            proportions = proportions / proportions.sum()
        else:
            proportions = np.array(
                [
                    float(mixture.healthy_stable.value),
                    float(mixture.healthy_noisy.value),
                    float(mixture.gradual_drift.value),
                    float(mixture.accelerated_drift.value),
                    float(mixture.early_latent_defect.value),
                    float(mixture.sudden_failure.value),
                    float(mixture.sensor_noise_anomaly.value),
                ]
            )
            proportions = proportions / proportions.sum()

        drawn_classes = self.rng.choice(classes, size=n_parts, p=proportions)
        parts = []

        for idx, d_class in enumerate(drawn_classes):
            p_id = f"C-{lot_id}-{idx + 1:04d}"
            sock = f"SOCK-{(idx % 16) + 1:02d}"

            if d_class == DegradationClass.EARLY_LATENT_DEFECT:
                # 50% chance of joint-only factor anomaly per DATA_GENERATION_SPEC § 5.1
                joint = bool(
                    self.rng.uniform(0.0, 1.0) < float(self.config.factors.joint_only_ratio.value)
                )
                part = self.generate_s1_escape_anomaly(
                    component_id=p_id,
                    lot_id=lot_id,
                    component_type=c_type,
                    is_joint_only=joint,
                    lot_centre=base_centres,
                    thermal_zone=thermal_zone,
                    socket_id=sock,
                )
            elif d_class == DegradationClass.ACCELERATED_DRIFT:
                part = self.generate_s2_escape_drift(
                    component_id=p_id,
                    lot_id=lot_id,
                    component_type=c_type,
                    lot_centre=base_centres,
                    thermal_zone=thermal_zone,
                    socket_id=sock,
                )
            elif d_class == DegradationClass.HEALTHY_NOISY:
                part = self.generate_s3_decoy_healthy(
                    component_id=p_id,
                    lot_id=lot_id,
                    component_type=c_type,
                    variant="noisy",
                    lot_centre=base_centres,
                    thermal_zone=thermal_zone,
                    socket_id=sock,
                )
            elif d_class == DegradationClass.GRADUAL_DRIFT:
                part = self.generate_s3_decoy_healthy(
                    component_id=p_id,
                    lot_id=lot_id,
                    component_type=c_type,
                    variant="gradual_drift",
                    lot_centre=base_centres,
                    thermal_zone=thermal_zone,
                    socket_id=sock,
                )
            elif d_class == DegradationClass.SENSOR_NOISE_ANOMALY:
                part = self.generate_s4_decoy_sensor(
                    component_id=p_id,
                    lot_id=lot_id,
                    component_type=c_type,
                    lot_centre=base_centres,
                    thermal_zone=thermal_zone,
                    socket_id=sock,
                )
            elif d_class == DegradationClass.SUDDEN_FAILURE:
                part = self.generate_s0_clear_fail(
                    component_id=p_id,
                    lot_id=lot_id,
                    component_type=c_type,
                    mechanism="sudden_failure",
                    lot_centre=base_centres,
                    thermal_zone=thermal_zone,
                    socket_id=sock,
                )
            else:
                # HEALTHY_STABLE
                part = self.generate_s3_decoy_healthy(
                    component_id=p_id,
                    lot_id=lot_id,
                    component_type=c_type,
                    variant="upper_tail" if self.rng.uniform(0.0, 1.0) < 0.15 else "noisy",
                    lot_centre=base_centres,
                    thermal_zone=thermal_zone,
                    socket_id=sock,
                )

            parts.append(part)

        return StratifiedLot(
            lot_id=lot_id,
            component_type=c_type,
            parts=parts,
            lot_centre=base_centres,
            is_shifted_lot=False,
            shift_magnitude=0.0,
        )


__all__ = [
    "DECOY_STRATA",
    "ESCAPE_STRATA",
    "FLAGGED_TARGET_STRATA",
    "FailureLabel",
    "StrataGenerator",
    "StratifiedLot",
    "Stratum",
    "StratumPart",
    "check_values_inside_limits",
    "classify_rendered_stratum",
    "find_limit_violations",
    "is_decoy",
    "is_escape",
    "must_flag",
]
